// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nds/audit/rationale.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nds.Audit {

  /// <summary>Holder for reflection information generated from nds/audit/rationale.proto</summary>
  public static partial class RationaleReflection {

    #region Descriptor
    /// <summary>File descriptor for nds/audit/rationale.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RationaleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChluZHMvYXVkaXQvcmF0aW9uYWxlLnByb3RvEgluZHMuYXVkaXQaF25kcy9j",
            "b21tb24vY29tbW9uLnByb3RvGhVuZHMvZXZlbnQvZXZlbnQucHJvdG8i3QMK",
            "DE5kc1JhdGlvbmFsZRIWCgZzb3VyY2UYASABKAlSBnNvdXJjZRI4Cgpjb25m",
            "aWRlbmNlGAIgASgLMhMubmRzLmNvbW1vbi5EZWNpbWFsSABSCmNvbmZpZGVu",
            "Y2WIAQESIQoMdGhvdWdodF9wYXRoGAMgAygJUgt0aG91Z2h0UGF0aBJAChJl",
            "dmlkZW5jZV9ldmVudF9pZHMYBCADKAsyEi5uZHMuZXZlbnQuRXZlbnRJZFIQ",
            "ZXZpZGVuY2VFdmVudElkcxI/Cg1ldmlkZW5jZV9yZWZzGAggAygLMhoubmRz",
            "LmF1ZGl0Lk5kc1JhdGlvbmFsZVJlZlIMZXZpZGVuY2VSZWZzEjcKCnJpc2tf",
            "c2NvcmUYBSABKAsyEy5uZHMuY29tbW9uLkRlY2ltYWxIAVIJcmlza1Njb3Jl",
            "iAEBEkEKCG1ldGFkYXRhGAYgAygLMiUubmRzLmF1ZGl0Lk5kc1JhdGlvbmFs",
            "ZS5NZXRhZGF0YUVudHJ5UghtZXRhZGF0YRo7Cg1NZXRhZGF0YUVudHJ5EhAK",
            "A2tleRgBIAEoCVIDa2V5EhQKBXZhbHVlGAIgASgJUgV2YWx1ZToCOAFCDQoL",
            "X2NvbmZpZGVuY2VCDQoLX3Jpc2tfc2NvcmUidQoPTmRzUmF0aW9uYWxlUmVm",
            "EhAKA3VyaRgBIAEoCVIDdXJpEhcKBGhhc2gYAiABKAlIAFIEaGFzaIgBARIg",
            "CgltaW1lX3R5cGUYAyABKAlIAVIIbWltZVR5cGWIAQFCBwoFX2hhc2hCDAoK",
            "X21pbWVfdHlwZUJkCg1jb20ubmRzLmF1ZGl0Qg5SYXRpb25hbGVQcm90b1AB",
            "ogIDTkFYqgIJTmRzLkF1ZGl0ygIJTmRzXEF1ZGl04gIVTmRzXEF1ZGl0XEdQ",
            "Qk1ldGFkYXRh6gIKTmRzOjpBdWRpdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Nds.Common.CommonReflection.Descriptor, global::Nds.Event.EventReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nds.Audit.NdsRationale), global::Nds.Audit.NdsRationale.Parser, new[]{ "Source", "Confidence", "ThoughtPath", "EvidenceEventIds", "EvidenceRefs", "RiskScore", "Metadata" }, new[]{ "Confidence", "RiskScore" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nds.Audit.NdsRationaleRef), global::Nds.Audit.NdsRationaleRef.Parser, new[]{ "Uri", "Hash", "MimeType" }, new[]{ "Hash", "MimeType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// [Semantic] Lightweight structured rationale (safe to embed).
  /// [Behavior] Not a full chain-of-thought; keep it auditable and compact.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NdsRationale : pb::IMessage<NdsRationale>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NdsRationale> _parser = new pb::MessageParser<NdsRationale>(() => new NdsRationale());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NdsRationale> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nds.Audit.RationaleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NdsRationale() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NdsRationale(NdsRationale other) : this() {
      source_ = other.source_;
      confidence_ = other.confidence_ != null ? other.confidence_.Clone() : null;
      thoughtPath_ = other.thoughtPath_.Clone();
      evidenceEventIds_ = other.evidenceEventIds_.Clone();
      evidenceRefs_ = other.evidenceRefs_.Clone();
      riskScore_ = other.riskScore_ != null ? other.riskScore_.Clone() : null;
      metadata_ = other.metadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NdsRationale Clone() {
      return new NdsRationale(this);
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 1;
    private string source_ = "";
    /// <summary>
    /// Who/what produced this rationale (e.g. "rule_engine_v1", "human_admin").
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Source {
      get { return source_; }
      set {
        source_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "confidence" field.</summary>
    public const int ConfidenceFieldNumber = 2;
    private global::Nds.Common.Decimal confidence_;
    /// <summary>
    /// Confidence score in [0,1] encoded as Decimal string (exact, language-neutral).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nds.Common.Decimal Confidence {
      get { return confidence_; }
      set {
        confidence_ = value;
      }
    }

    /// <summary>Field number for the "thought_path" field.</summary>
    public const int ThoughtPathFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_thoughtPath_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> thoughtPath_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Short structured steps.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ThoughtPath {
      get { return thoughtPath_; }
    }

    /// <summary>Field number for the "evidence_event_ids" field.</summary>
    public const int EvidenceEventIdsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Nds.Event.EventId> _repeated_evidenceEventIds_codec
        = pb::FieldCodec.ForMessage(34, global::Nds.Event.EventId.Parser);
    private readonly pbc::RepeatedField<global::Nds.Event.EventId> evidenceEventIds_ = new pbc::RepeatedField<global::Nds.Event.EventId>();
    /// <summary>
    /// Evidence references (within the same resolvable event space).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Nds.Event.EventId> EvidenceEventIds {
      get { return evidenceEventIds_; }
    }

    /// <summary>Field number for the "evidence_refs" field.</summary>
    public const int EvidenceRefsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Nds.Audit.NdsRationaleRef> _repeated_evidenceRefs_codec
        = pb::FieldCodec.ForMessage(66, global::Nds.Audit.NdsRationaleRef.Parser);
    private readonly pbc::RepeatedField<global::Nds.Audit.NdsRationaleRef> evidenceRefs_ = new pbc::RepeatedField<global::Nds.Audit.NdsRationaleRef>();
    /// <summary>
    /// Cross-system evidence references (URI-based).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Nds.Audit.NdsRationaleRef> EvidenceRefs {
      get { return evidenceRefs_; }
    }

    /// <summary>Field number for the "risk_score" field.</summary>
    public const int RiskScoreFieldNumber = 5;
    private global::Nds.Common.Decimal riskScore_;
    /// <summary>
    /// Optional risk indicator (protocol does not define semantics/range).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nds.Common.Decimal RiskScore {
      get { return riskScore_; }
      set {
        riskScore_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 6;
    private static readonly pbc::MapField<string, string>.Codec _map_metadata_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 50);
    private readonly pbc::MapField<string, string> metadata_ = new pbc::MapField<string, string>();
    /// <summary>
    /// Extension slot.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Metadata {
      get { return metadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NdsRationale);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NdsRationale other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Source != other.Source) return false;
      if (!object.Equals(Confidence, other.Confidence)) return false;
      if(!thoughtPath_.Equals(other.thoughtPath_)) return false;
      if(!evidenceEventIds_.Equals(other.evidenceEventIds_)) return false;
      if(!evidenceRefs_.Equals(other.evidenceRefs_)) return false;
      if (!object.Equals(RiskScore, other.RiskScore)) return false;
      if (!Metadata.Equals(other.Metadata)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Source.Length != 0) hash ^= Source.GetHashCode();
      if (confidence_ != null) hash ^= Confidence.GetHashCode();
      hash ^= thoughtPath_.GetHashCode();
      hash ^= evidenceEventIds_.GetHashCode();
      hash ^= evidenceRefs_.GetHashCode();
      if (riskScore_ != null) hash ^= RiskScore.GetHashCode();
      hash ^= Metadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Source.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Source);
      }
      if (confidence_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Confidence);
      }
      thoughtPath_.WriteTo(output, _repeated_thoughtPath_codec);
      evidenceEventIds_.WriteTo(output, _repeated_evidenceEventIds_codec);
      if (riskScore_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RiskScore);
      }
      metadata_.WriteTo(output, _map_metadata_codec);
      evidenceRefs_.WriteTo(output, _repeated_evidenceRefs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Source.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Source);
      }
      if (confidence_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Confidence);
      }
      thoughtPath_.WriteTo(ref output, _repeated_thoughtPath_codec);
      evidenceEventIds_.WriteTo(ref output, _repeated_evidenceEventIds_codec);
      if (riskScore_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RiskScore);
      }
      metadata_.WriteTo(ref output, _map_metadata_codec);
      evidenceRefs_.WriteTo(ref output, _repeated_evidenceRefs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Source.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Source);
      }
      if (confidence_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Confidence);
      }
      size += thoughtPath_.CalculateSize(_repeated_thoughtPath_codec);
      size += evidenceEventIds_.CalculateSize(_repeated_evidenceEventIds_codec);
      size += evidenceRefs_.CalculateSize(_repeated_evidenceRefs_codec);
      if (riskScore_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RiskScore);
      }
      size += metadata_.CalculateSize(_map_metadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NdsRationale other) {
      if (other == null) {
        return;
      }
      if (other.Source.Length != 0) {
        Source = other.Source;
      }
      if (other.confidence_ != null) {
        if (confidence_ == null) {
          Confidence = new global::Nds.Common.Decimal();
        }
        Confidence.MergeFrom(other.Confidence);
      }
      thoughtPath_.Add(other.thoughtPath_);
      evidenceEventIds_.Add(other.evidenceEventIds_);
      evidenceRefs_.Add(other.evidenceRefs_);
      if (other.riskScore_ != null) {
        if (riskScore_ == null) {
          RiskScore = new global::Nds.Common.Decimal();
        }
        RiskScore.MergeFrom(other.RiskScore);
      }
      metadata_.MergeFrom(other.metadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Source = input.ReadString();
            break;
          }
          case 18: {
            if (confidence_ == null) {
              Confidence = new global::Nds.Common.Decimal();
            }
            input.ReadMessage(Confidence);
            break;
          }
          case 26: {
            thoughtPath_.AddEntriesFrom(input, _repeated_thoughtPath_codec);
            break;
          }
          case 34: {
            evidenceEventIds_.AddEntriesFrom(input, _repeated_evidenceEventIds_codec);
            break;
          }
          case 42: {
            if (riskScore_ == null) {
              RiskScore = new global::Nds.Common.Decimal();
            }
            input.ReadMessage(RiskScore);
            break;
          }
          case 50: {
            metadata_.AddEntriesFrom(input, _map_metadata_codec);
            break;
          }
          case 66: {
            evidenceRefs_.AddEntriesFrom(input, _repeated_evidenceRefs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Source = input.ReadString();
            break;
          }
          case 18: {
            if (confidence_ == null) {
              Confidence = new global::Nds.Common.Decimal();
            }
            input.ReadMessage(Confidence);
            break;
          }
          case 26: {
            thoughtPath_.AddEntriesFrom(ref input, _repeated_thoughtPath_codec);
            break;
          }
          case 34: {
            evidenceEventIds_.AddEntriesFrom(ref input, _repeated_evidenceEventIds_codec);
            break;
          }
          case 42: {
            if (riskScore_ == null) {
              RiskScore = new global::Nds.Common.Decimal();
            }
            input.ReadMessage(RiskScore);
            break;
          }
          case 50: {
            metadata_.AddEntriesFrom(ref input, _map_metadata_codec);
            break;
          }
          case 66: {
            evidenceRefs_.AddEntriesFrom(ref input, _repeated_evidenceRefs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// [Semantic] External rationale/evidence reference for heavy payloads.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NdsRationaleRef : pb::IMessage<NdsRationaleRef>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NdsRationaleRef> _parser = new pb::MessageParser<NdsRationaleRef>(() => new NdsRationaleRef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NdsRationaleRef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nds.Audit.RationaleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NdsRationaleRef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NdsRationaleRef(NdsRationaleRef other) : this() {
      uri_ = other.uri_;
      hash_ = other.hash_;
      mimeType_ = other.mimeType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NdsRationaleRef Clone() {
      return new NdsRationaleRef(this);
    }

    /// <summary>Field number for the "uri" field.</summary>
    public const int UriFieldNumber = 1;
    private string uri_ = "";
    /// <summary>
    /// URI (e.g. "https://.../report.json", "ipfs://...", "file://...").
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uri {
      get { return uri_; }
      set {
        uri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hash" field.</summary>
    public const int HashFieldNumber = 2;
    private readonly static string HashDefaultValue = "";

    private string hash_;
    /// <summary>
    /// Optional content hash (e.g. sha256 hex) for integrity.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Hash {
      get { return hash_ ?? HashDefaultValue; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "hash" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHash {
      get { return hash_ != null; }
    }
    /// <summary>Clears the value of the "hash" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHash() {
      hash_ = null;
    }

    /// <summary>Field number for the "mime_type" field.</summary>
    public const int MimeTypeFieldNumber = 3;
    private readonly static string MimeTypeDefaultValue = "";

    private string mimeType_;
    /// <summary>
    /// Optional mime type (e.g. "application/json").
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MimeType {
      get { return mimeType_ ?? MimeTypeDefaultValue; }
      set {
        mimeType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "mime_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMimeType {
      get { return mimeType_ != null; }
    }
    /// <summary>Clears the value of the "mime_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMimeType() {
      mimeType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NdsRationaleRef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NdsRationaleRef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uri != other.Uri) return false;
      if (Hash != other.Hash) return false;
      if (MimeType != other.MimeType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uri.Length != 0) hash ^= Uri.GetHashCode();
      if (HasHash) hash ^= Hash.GetHashCode();
      if (HasMimeType) hash ^= MimeType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uri.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uri);
      }
      if (HasHash) {
        output.WriteRawTag(18);
        output.WriteString(Hash);
      }
      if (HasMimeType) {
        output.WriteRawTag(26);
        output.WriteString(MimeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uri.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uri);
      }
      if (HasHash) {
        output.WriteRawTag(18);
        output.WriteString(Hash);
      }
      if (HasMimeType) {
        output.WriteRawTag(26);
        output.WriteString(MimeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uri.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uri);
      }
      if (HasHash) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hash);
      }
      if (HasMimeType) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MimeType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NdsRationaleRef other) {
      if (other == null) {
        return;
      }
      if (other.Uri.Length != 0) {
        Uri = other.Uri;
      }
      if (other.HasHash) {
        Hash = other.Hash;
      }
      if (other.HasMimeType) {
        MimeType = other.MimeType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uri = input.ReadString();
            break;
          }
          case 18: {
            Hash = input.ReadString();
            break;
          }
          case 26: {
            MimeType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Uri = input.ReadString();
            break;
          }
          case 18: {
            Hash = input.ReadString();
            break;
          }
          case 26: {
            MimeType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
