// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nds/identity/v1/identity_v1.proto
// Protobuf C++ Version: 6.33.5

#include "nds/identity/v1/identity_v1.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nds {
namespace identity {
namespace v1 {

inline constexpr PersonaId::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PersonaId::PersonaId(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PersonaId_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PersonaIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PersonaIdDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PersonaIdDefaultTypeInternal() {}
  union {
    PersonaId _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PersonaIdDefaultTypeInternal _PersonaId_default_instance_;

inline constexpr ExternalAccountBinding::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        external_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        binding_proof_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        provider_{static_cast< ::nds::identity::v1::ExternalProvider >(0)},
        verified_level_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ExternalAccountBinding::ExternalAccountBinding(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ExternalAccountBinding_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ExternalAccountBindingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExternalAccountBindingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExternalAccountBindingDefaultTypeInternal() {}
  union {
    ExternalAccountBinding _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExternalAccountBindingDefaultTypeInternal _ExternalAccountBinding_default_instance_;

inline constexpr Persona::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bindings_{},
        id_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Persona::Persona(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Persona_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PersonaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PersonaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PersonaDefaultTypeInternal() {}
  union {
    Persona _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PersonaDefaultTypeInternal _Persona_default_instance_;
}  // namespace v1
}  // namespace identity
}  // namespace nds
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto = nullptr;
const ::uint32_t
    TableStruct_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::PersonaId, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::PersonaId, _impl_.value_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::ExternalAccountBinding, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::ExternalAccountBinding, _impl_.provider_),
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::ExternalAccountBinding, _impl_.external_id_),
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::ExternalAccountBinding, _impl_.verified_level_),
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::ExternalAccountBinding, _impl_.binding_proof_),
        2,
        0,
        3,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::Persona, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::Persona, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::nds::identity::v1::Persona, _impl_.bindings_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::nds::identity::v1::PersonaId)},
        {5, sizeof(::nds::identity::v1::ExternalAccountBinding)},
        {16, sizeof(::nds::identity::v1::Persona)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::nds::identity::v1::_PersonaId_default_instance_._instance,
    &::nds::identity::v1::_ExternalAccountBinding_default_instance_._instance,
    &::nds::identity::v1::_Persona_default_instance_._instance,
};
const char descriptor_table_protodef_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n!nds/identity/v1/identity_v1.proto\022\017nds"
    ".identity.v1\"!\n\tPersonaId\022\024\n\005value\030\001 \001(\014"
    "R\005value\"\304\001\n\026ExternalAccountBinding\022=\n\010pr"
    "ovider\030\001 \001(\0162!.nds.identity.v1.ExternalP"
    "roviderR\010provider\022\037\n\013external_id\030\002 \001(\tR\n"
    "externalId\022%\n\016verified_level\030\003 \001(\005R\rveri"
    "fiedLevel\022#\n\rbinding_proof\030\004 \001(\014R\014bindin"
    "gProof\"z\n\007Persona\022*\n\002id\030\001 \001(\0132\032.nds.iden"
    "tity.v1.PersonaIdR\002id\022C\n\010bindings\030\002 \003(\0132"
    "\'.nds.identity.v1.ExternalAccountBinding"
    "R\010bindings*\257\001\n\020ExternalProvider\022!\n\035EXTER"
    "NAL_PROVIDER_UNSPECIFIED\020\000\022\037\n\033EXTERNAL_P"
    "ROVIDER_MINECRAFT\020\001\022\035\n\031EXTERNAL_PROVIDER"
    "_DISCORD\020\002\022\032\n\026EXTERNAL_PROVIDER_OIDC\020\003\022\034"
    "\n\030EXTERNAL_PROVIDER_DEVICE\020\004B\347\001\n:noie.li"
    "nmimeng.noiedigitalsystem.api.proto.nds."
    "identity.v1B\017IdentityV1ProtoP\001Z:github.c"
    "om/misty4119/nds-api/Go/nds/identity/v1;"
    "identityv1\242\002\003NIX\252\002\017Nds.Identity.V1\312\002\017Nds"
    "\\Identity\\V1\342\002\033Nds\\Identity\\V1\\GPBMetada"
    "ta\352\002\021Nds::Identity::V1b\006proto3"
};
static ::absl::once_flag descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto = {
    false,
    false,
    830,
    descriptor_table_protodef_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto,
    "nds/identity/v1/identity_v1.proto",
    &descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto::offsets,
    file_level_enum_descriptors_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto,
    file_level_service_descriptors_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto,
};
namespace nds {
namespace identity {
namespace v1 {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ExternalProvider_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto);
  return file_level_enum_descriptors_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ExternalProvider_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

class PersonaId::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PersonaId>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PersonaId, _impl_._has_bits_);
};

PersonaId::PersonaId(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PersonaId_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.identity.v1.PersonaId)
}
PROTOBUF_NDEBUG_INLINE PersonaId::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::identity::v1::PersonaId& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_(arena, from.value_) {}

PersonaId::PersonaId(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PersonaId& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PersonaId_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PersonaId* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nds.identity.v1.PersonaId)
}
PROTOBUF_NDEBUG_INLINE PersonaId::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        value_(arena) {}

inline void PersonaId::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PersonaId::~PersonaId() {
  // @@protoc_insertion_point(destructor:nds.identity.v1.PersonaId)
  SharedDtor(*this);
}
inline void PersonaId::SharedDtor(MessageLite& self) {
  PersonaId& this_ = static_cast<PersonaId&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PersonaId::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PersonaId(arena);
}
constexpr auto PersonaId::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PersonaId),
                                            alignof(PersonaId));
}
constexpr auto PersonaId::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PersonaId_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PersonaId::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PersonaId>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PersonaId::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PersonaId>(), &PersonaId::ByteSizeLong,
              &PersonaId::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PersonaId, _impl_._cached_size_),
          false,
      },
      &PersonaId::kDescriptorMethods,
      &descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PersonaId_class_data_ =
        PersonaId::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PersonaId::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PersonaId_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PersonaId_class_data_.tc_table);
  return PersonaId_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PersonaId::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PersonaId, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PersonaId_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::identity::v1::PersonaId>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes value = 1 [json_name = "value"];
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PersonaId, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes value = 1 [json_name = "value"];
    {PROTOBUF_FIELD_OFFSET(PersonaId, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PersonaId::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.identity.v1.PersonaId)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.value_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PersonaId::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PersonaId& this_ = static_cast<const PersonaId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PersonaId::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PersonaId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.identity.v1.PersonaId)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes value = 1 [json_name = "value"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.identity.v1.PersonaId)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PersonaId::ByteSizeLong(const MessageLite& base) {
  const PersonaId& this_ = static_cast<const PersonaId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PersonaId::ByteSizeLong() const {
  const PersonaId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.identity.v1.PersonaId)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bytes value = 1 [json_name = "value"];
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PersonaId::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PersonaId*>(&to_msg);
  auto& from = static_cast<const PersonaId&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.identity.v1.PersonaId)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_value().empty()) {
      _this->_internal_set_value(from._internal_value());
    } else {
      if (_this->_impl_.value_.IsDefault()) {
        _this->_internal_set_value("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PersonaId::CopyFrom(const PersonaId& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.identity.v1.PersonaId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PersonaId::InternalSwap(PersonaId* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata PersonaId::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ExternalAccountBinding::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ExternalAccountBinding>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_._has_bits_);
};

ExternalAccountBinding::ExternalAccountBinding(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ExternalAccountBinding_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.identity.v1.ExternalAccountBinding)
}
PROTOBUF_NDEBUG_INLINE ExternalAccountBinding::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::identity::v1::ExternalAccountBinding& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        external_id_(arena, from.external_id_),
        binding_proof_(arena, from.binding_proof_) {}

ExternalAccountBinding::ExternalAccountBinding(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ExternalAccountBinding& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ExternalAccountBinding_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ExternalAccountBinding* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, provider_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, provider_),
           offsetof(Impl_, verified_level_) -
               offsetof(Impl_, provider_) +
               sizeof(Impl_::verified_level_));

  // @@protoc_insertion_point(copy_constructor:nds.identity.v1.ExternalAccountBinding)
}
PROTOBUF_NDEBUG_INLINE ExternalAccountBinding::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        external_id_(arena),
        binding_proof_(arena) {}

inline void ExternalAccountBinding::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, provider_),
           0,
           offsetof(Impl_, verified_level_) -
               offsetof(Impl_, provider_) +
               sizeof(Impl_::verified_level_));
}
ExternalAccountBinding::~ExternalAccountBinding() {
  // @@protoc_insertion_point(destructor:nds.identity.v1.ExternalAccountBinding)
  SharedDtor(*this);
}
inline void ExternalAccountBinding::SharedDtor(MessageLite& self) {
  ExternalAccountBinding& this_ = static_cast<ExternalAccountBinding&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.external_id_.Destroy();
  this_._impl_.binding_proof_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ExternalAccountBinding::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ExternalAccountBinding(arena);
}
constexpr auto ExternalAccountBinding::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ExternalAccountBinding),
                                            alignof(ExternalAccountBinding));
}
constexpr auto ExternalAccountBinding::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ExternalAccountBinding_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ExternalAccountBinding::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ExternalAccountBinding>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ExternalAccountBinding::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ExternalAccountBinding>(), &ExternalAccountBinding::ByteSizeLong,
              &ExternalAccountBinding::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_._cached_size_),
          false,
      },
      &ExternalAccountBinding::kDescriptorMethods,
      &descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ExternalAccountBinding_class_data_ =
        ExternalAccountBinding::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ExternalAccountBinding::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ExternalAccountBinding_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ExternalAccountBinding_class_data_.tc_table);
  return ExternalAccountBinding_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 58, 2>
ExternalAccountBinding::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ExternalAccountBinding_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::identity::v1::ExternalAccountBinding>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes binding_proof = 4 [json_name = "bindingProof"];
    {::_pbi::TcParser::FastBS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.binding_proof_)}},
    // .nds.identity.v1.ExternalProvider provider = 1 [json_name = "provider"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExternalAccountBinding, _impl_.provider_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.provider_)}},
    // string external_id = 2 [json_name = "externalId"];
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.external_id_)}},
    // int32 verified_level = 3 [json_name = "verifiedLevel"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExternalAccountBinding, _impl_.verified_level_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.verified_level_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nds.identity.v1.ExternalProvider provider = 1 [json_name = "provider"];
    {PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.provider_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string external_id = 2 [json_name = "externalId"];
    {PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.external_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 verified_level = 3 [json_name = "verifiedLevel"];
    {PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.verified_level_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bytes binding_proof = 4 [json_name = "bindingProof"];
    {PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.binding_proof_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\46\0\13\0\0\0\0\0"
    "nds.identity.v1.ExternalAccountBinding"
    "external_id"
  }},
};
PROTOBUF_NOINLINE void ExternalAccountBinding::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.identity.v1.ExternalAccountBinding)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.external_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.binding_proof_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.provider_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.verified_level_) -
        reinterpret_cast<char*>(&_impl_.provider_)) + sizeof(_impl_.verified_level_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ExternalAccountBinding::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ExternalAccountBinding& this_ = static_cast<const ExternalAccountBinding&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ExternalAccountBinding::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ExternalAccountBinding& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.identity.v1.ExternalAccountBinding)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .nds.identity.v1.ExternalProvider provider = 1 [json_name = "provider"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_provider() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_provider(), target);
    }
  }

  // string external_id = 2 [json_name = "externalId"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_external_id().empty()) {
      const ::std::string& _s = this_._internal_external_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.identity.v1.ExternalAccountBinding.external_id");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int32 verified_level = 3 [json_name = "verifiedLevel"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_verified_level() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_verified_level(), target);
    }
  }

  // bytes binding_proof = 4 [json_name = "bindingProof"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_binding_proof().empty()) {
      const ::std::string& _s = this_._internal_binding_proof();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.identity.v1.ExternalAccountBinding)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ExternalAccountBinding::ByteSizeLong(const MessageLite& base) {
  const ExternalAccountBinding& this_ = static_cast<const ExternalAccountBinding&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ExternalAccountBinding::ByteSizeLong() const {
  const ExternalAccountBinding& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.identity.v1.ExternalAccountBinding)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string external_id = 2 [json_name = "externalId"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_external_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_external_id());
      }
    }
    // bytes binding_proof = 4 [json_name = "bindingProof"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_binding_proof().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_binding_proof());
      }
    }
    // .nds.identity.v1.ExternalProvider provider = 1 [json_name = "provider"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_provider() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_provider());
      }
    }
    // int32 verified_level = 3 [json_name = "verifiedLevel"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_verified_level() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_verified_level());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ExternalAccountBinding::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ExternalAccountBinding*>(&to_msg);
  auto& from = static_cast<const ExternalAccountBinding&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.identity.v1.ExternalAccountBinding)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_external_id().empty()) {
        _this->_internal_set_external_id(from._internal_external_id());
      } else {
        if (_this->_impl_.external_id_.IsDefault()) {
          _this->_internal_set_external_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_binding_proof().empty()) {
        _this->_internal_set_binding_proof(from._internal_binding_proof());
      } else {
        if (_this->_impl_.binding_proof_.IsDefault()) {
          _this->_internal_set_binding_proof("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_provider() != 0) {
        _this->_impl_.provider_ = from._impl_.provider_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_verified_level() != 0) {
        _this->_impl_.verified_level_ = from._impl_.verified_level_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ExternalAccountBinding::CopyFrom(const ExternalAccountBinding& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.identity.v1.ExternalAccountBinding)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ExternalAccountBinding::InternalSwap(ExternalAccountBinding* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.external_id_, &other->_impl_.external_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.binding_proof_, &other->_impl_.binding_proof_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.verified_level_)
      + sizeof(ExternalAccountBinding::_impl_.verified_level_)
      - PROTOBUF_FIELD_OFFSET(ExternalAccountBinding, _impl_.provider_)>(
          reinterpret_cast<char*>(&_impl_.provider_),
          reinterpret_cast<char*>(&other->_impl_.provider_));
}

::google::protobuf::Metadata ExternalAccountBinding::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Persona::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Persona>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Persona, _impl_._has_bits_);
};

Persona::Persona(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Persona_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.identity.v1.Persona)
}
PROTOBUF_NDEBUG_INLINE Persona::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::identity::v1::Persona& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        bindings_{visibility, arena, from.bindings_} {}

Persona::Persona(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Persona& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Persona_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Persona* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.id_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.id_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:nds.identity.v1.Persona)
}
PROTOBUF_NDEBUG_INLINE Persona::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        bindings_{visibility, arena} {}

inline void Persona::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Persona::~Persona() {
  // @@protoc_insertion_point(destructor:nds.identity.v1.Persona)
  SharedDtor(*this);
}
inline void Persona::SharedDtor(MessageLite& self) {
  Persona& this_ = static_cast<Persona&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.id_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Persona::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Persona(arena);
}
constexpr auto Persona::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Persona, _impl_.bindings_) +
          decltype(Persona::_impl_.bindings_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Persona), alignof(Persona), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Persona::PlacementNew_,
                                 sizeof(Persona),
                                 alignof(Persona));
  }
}
constexpr auto Persona::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Persona_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Persona::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Persona>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Persona::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Persona>(), &Persona::ByteSizeLong,
              &Persona::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Persona, _impl_._cached_size_),
          false,
      },
      &Persona::kDescriptorMethods,
      &descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Persona_class_data_ =
        Persona::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Persona::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Persona_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Persona_class_data_.tc_table);
  return Persona_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
Persona::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Persona, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Persona_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::identity::v1::Persona>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .nds.identity.v1.ExternalAccountBinding bindings = 2 [json_name = "bindings"];
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 1,
      PROTOBUF_FIELD_OFFSET(Persona, _impl_.bindings_)}},
    // .nds.identity.v1.PersonaId id = 1 [json_name = "id"];
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(Persona, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nds.identity.v1.PersonaId id = 1 [json_name = "id"];
    {PROTOBUF_FIELD_OFFSET(Persona, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .nds.identity.v1.ExternalAccountBinding bindings = 2 [json_name = "bindings"];
    {PROTOBUF_FIELD_OFFSET(Persona, _impl_.bindings_), _Internal::kHasBitsOffset + 0, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::nds::identity::v1::PersonaId>()},
      {::_pbi::TcParser::GetTable<::nds::identity::v1::ExternalAccountBinding>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Persona::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.identity.v1.Persona)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.bindings_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.id_ != nullptr);
      _impl_.id_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Persona::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Persona& this_ = static_cast<const Persona&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Persona::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Persona& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.identity.v1.Persona)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .nds.identity.v1.PersonaId id = 1 [json_name = "id"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.id_, this_._impl_.id_->GetCachedSize(), target,
        stream);
  }

  // repeated .nds.identity.v1.ExternalAccountBinding bindings = 2 [json_name = "bindings"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_bindings_size());
         i < n; i++) {
      const auto& repfield = this_._internal_bindings().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.identity.v1.Persona)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Persona::ByteSizeLong(const MessageLite& base) {
  const Persona& this_ = static_cast<const Persona&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Persona::ByteSizeLong() const {
  const Persona& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.identity.v1.Persona)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .nds.identity.v1.ExternalAccountBinding bindings = 2 [json_name = "bindings"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_bindings_size();
      for (const auto& msg : this_._internal_bindings()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // .nds.identity.v1.PersonaId id = 1 [json_name = "id"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.id_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Persona::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Persona*>(&to_msg);
  auto& from = static_cast<const Persona&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.identity.v1.Persona)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_bindings()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_bindings());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.id_ != nullptr);
      if (_this->_impl_.id_ == nullptr) {
        _this->_impl_.id_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.id_);
      } else {
        _this->_impl_.id_->MergeFrom(*from._impl_.id_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Persona::CopyFrom(const Persona& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.identity.v1.Persona)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Persona::InternalSwap(Persona* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.bindings_.InternalSwap(&other->_impl_.bindings_);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Persona::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace identity
}  // namespace nds
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
