// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies
// @generated from protobuf file "nds/identity/v1/identity_v1.proto" (package "nds.identity.v1", syntax proto3)
// tslint:disable
//
// [Module] NDS Protocol
// [Component] identity_v1.proto
// [Layer] Contract (language-agnostic)
// [Index] NDS-PROTO-IDENTITY-V1-000
// [Semantic] v3+ identity model: Persona + external bindings.
// [Since] 3.0.0
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// ============================================================================
// [Index] NDS-PROTO-IDENTITY-V1-010 PersonaId
// ============================================================================

/**
 * [Semantic] Internal stable identity key representing the "same person" across platforms.
 * [Invariant] MUST be treated as opaque bytes on the wire (no string concatenation parsing).
 *
 * @generated from protobuf message nds.identity.v1.PersonaId
 */
export interface PersonaId {
    /**
     * @generated from protobuf field: bytes value = 1
     */
    value: Uint8Array;
}
/**
 * [Semantic] A verifiable binding between a Persona and an external account identifier.
 *
 * @generated from protobuf message nds.identity.v1.ExternalAccountBinding
 */
export interface ExternalAccountBinding {
    /**
     * @generated from protobuf field: nds.identity.v1.ExternalProvider provider = 1
     */
    provider: ExternalProvider;
    /**
     * Provider-specific external id.
     * [Example] Minecraft UUID, Discord snowflake, OIDC subject, device id.
     *
     * @generated from protobuf field: string external_id = 2
     */
    externalId: string;
    /**
     * Verification strength (0=unverified; higher=stronger).
     *
     * @generated from protobuf field: int32 verified_level = 3
     */
    verifiedLevel: number;
    /**
     * Opaque proof blob.
     * [Constraint] MUST NOT embed secrets (tokens/passwords/private keys).
     *
     * @generated from protobuf field: bytes binding_proof = 4
     */
    bindingProof: Uint8Array;
}
// ============================================================================
// [Index] NDS-PROTO-IDENTITY-V1-030 Persona
// ============================================================================

/**
 * @generated from protobuf message nds.identity.v1.Persona
 */
export interface Persona {
    /**
     * @generated from protobuf field: nds.identity.v1.PersonaId id = 1
     */
    id?: PersonaId;
    /**
     * @generated from protobuf field: repeated nds.identity.v1.ExternalAccountBinding bindings = 2
     */
    bindings: ExternalAccountBinding[];
}
// ============================================================================
// [Index] NDS-PROTO-IDENTITY-V1-020 ExternalAccountBinding
// ============================================================================

/**
 * @generated from protobuf enum nds.identity.v1.ExternalProvider
 */
export enum ExternalProvider {
    /**
     * @generated from protobuf enum value: EXTERNAL_PROVIDER_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: EXTERNAL_PROVIDER_MINECRAFT = 1;
     */
    MINECRAFT = 1,
    /**
     * @generated from protobuf enum value: EXTERNAL_PROVIDER_DISCORD = 2;
     */
    DISCORD = 2,
    /**
     * @generated from protobuf enum value: EXTERNAL_PROVIDER_OIDC = 3;
     */
    OIDC = 3,
    /**
     * @generated from protobuf enum value: EXTERNAL_PROVIDER_DEVICE = 4;
     */
    DEVICE = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class PersonaId$Type extends MessageType<PersonaId> {
    constructor() {
        super("nds.identity.v1.PersonaId", [
            { no: 1, name: "value", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<PersonaId>): PersonaId {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.value = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<PersonaId>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PersonaId): PersonaId {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes value */ 1:
                    message.value = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PersonaId, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes value = 1; */
        if (message.value.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.identity.v1.PersonaId
 */
export const PersonaId = new PersonaId$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExternalAccountBinding$Type extends MessageType<ExternalAccountBinding> {
    constructor() {
        super("nds.identity.v1.ExternalAccountBinding", [
            { no: 1, name: "provider", kind: "enum", T: () => ["nds.identity.v1.ExternalProvider", ExternalProvider, "EXTERNAL_PROVIDER_"] },
            { no: 2, name: "external_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "verified_level", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "binding_proof", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<ExternalAccountBinding>): ExternalAccountBinding {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.provider = 0;
        message.externalId = "";
        message.verifiedLevel = 0;
        message.bindingProof = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<ExternalAccountBinding>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExternalAccountBinding): ExternalAccountBinding {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.identity.v1.ExternalProvider provider */ 1:
                    message.provider = reader.int32();
                    break;
                case /* string external_id */ 2:
                    message.externalId = reader.string();
                    break;
                case /* int32 verified_level */ 3:
                    message.verifiedLevel = reader.int32();
                    break;
                case /* bytes binding_proof */ 4:
                    message.bindingProof = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExternalAccountBinding, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.identity.v1.ExternalProvider provider = 1; */
        if (message.provider !== 0)
            writer.tag(1, WireType.Varint).int32(message.provider);
        /* string external_id = 2; */
        if (message.externalId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.externalId);
        /* int32 verified_level = 3; */
        if (message.verifiedLevel !== 0)
            writer.tag(3, WireType.Varint).int32(message.verifiedLevel);
        /* bytes binding_proof = 4; */
        if (message.bindingProof.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.bindingProof);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.identity.v1.ExternalAccountBinding
 */
export const ExternalAccountBinding = new ExternalAccountBinding$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Persona$Type extends MessageType<Persona> {
    constructor() {
        super("nds.identity.v1.Persona", [
            { no: 1, name: "id", kind: "message", T: () => PersonaId },
            { no: 2, name: "bindings", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ExternalAccountBinding }
        ]);
    }
    create(value?: PartialMessage<Persona>): Persona {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.bindings = [];
        if (value !== undefined)
            reflectionMergePartial<Persona>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Persona): Persona {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.identity.v1.PersonaId id */ 1:
                    message.id = PersonaId.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* repeated nds.identity.v1.ExternalAccountBinding bindings */ 2:
                    message.bindings.push(ExternalAccountBinding.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Persona, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.identity.v1.PersonaId id = 1; */
        if (message.id)
            PersonaId.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated nds.identity.v1.ExternalAccountBinding bindings = 2; */
        for (let i = 0; i < message.bindings.length; i++)
            ExternalAccountBinding.internalBinaryWrite(message.bindings[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.identity.v1.Persona
 */
export const Persona = new Persona$Type();
