// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies
// @generated from protobuf file "nds/query/query.proto" (package "nds.query", syntax proto3)
// tslint:disable
//
// [Module] NDS Protocol
// [Component] query.proto
// [Layer] Contract (language-agnostic)
// [Index] NDS-PROTO-QUERY-000
// [Semantic] Read-only query service contract (projection-backed).
// [Constraint] Queries MUST NOT mutate state.
// [Constraint] Results MUST be derived from projections/event history, not direct mutable state.
// [Since] 2.0.0
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { NdsProjection } from "../projection/projection";
import { ProjectionId } from "../projection/projection";
import { NdsEvent } from "../event/event";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Decimal } from "../common/common";
import { NdsResult } from "../common/common";
import { NdsContext } from "../context/context";
import { NdsIdentity } from "../identity/identity";
import { AssetId } from "../asset/asset";
// ============================================================================
// [Index] NDS-PROTO-QUERY-100 Request/Response Messages
// ============================================================================

/**
 * [Index] NDS-PROTO-QUERY-110 QueryBalanceRequest
 *
 * @generated from protobuf message nds.query.QueryBalanceRequest
 */
export interface QueryBalanceRequest {
    /**
     * Asset ID.
     *
     * @generated from protobuf field: nds.asset.AssetId asset = 1
     */
    asset?: AssetId;
    /**
     * Identity (optional). If omitted, indicates a server-scoped asset query.
     *
     * @generated from protobuf field: optional nds.identity.NdsIdentity identity = 2
     */
    identity?: NdsIdentity;
    /**
     * Context (optional).
     *
     * @generated from protobuf field: optional nds.context.NdsContext context = 3
     */
    context?: NdsContext;
}
/**
 * [Index] NDS-PROTO-QUERY-120 QueryBalanceResponse
 *
 * @generated from protobuf message nds.query.QueryBalanceResponse
 */
export interface QueryBalanceResponse {
    /**
     * Result.
     *
     * @generated from protobuf field: nds.common.NdsResult result = 1
     */
    result?: NdsResult;
    /**
     * Balance (valid only on success).
     *
     * @generated from protobuf field: optional nds.common.Decimal balance = 2
     */
    balance?: Decimal;
}
/**
 * [Index] NDS-PROTO-QUERY-130 QueryHistoryRequest
 *
 * @generated from protobuf message nds.query.QueryHistoryRequest
 */
export interface QueryHistoryRequest {
    /**
     * Asset ID (optional). If omitted, queries across all assets.
     *
     * @generated from protobuf field: optional nds.asset.AssetId asset = 1
     */
    asset?: AssetId;
    /**
     * Identity (optional). If omitted, queries across all identities.
     *
     * @generated from protobuf field: optional nds.identity.NdsIdentity identity = 2
     */
    identity?: NdsIdentity;
    /**
     * Start time (optional).
     *
     * @generated from protobuf field: optional google.protobuf.Timestamp start_time = 3
     */
    startTime?: Timestamp;
    /**
     * End time (optional).
     *
     * @generated from protobuf field: optional google.protobuf.Timestamp end_time = 4
     */
    endTime?: Timestamp;
    /**
     * Limit.
     *
     * @generated from protobuf field: int32 limit = 5
     */
    limit: number;
    /**
     * Offset.
     *
     * @generated from protobuf field: int32 offset = 6
     */
    offset: number;
    /**
     * Context (optional).
     *
     * @generated from protobuf field: optional nds.context.NdsContext context = 7
     */
    context?: NdsContext;
}
/**
 * [Index] NDS-PROTO-QUERY-140 QueryHistoryResponse
 *
 * @generated from protobuf message nds.query.QueryHistoryResponse
 */
export interface QueryHistoryResponse {
    /**
     * Result.
     *
     * @generated from protobuf field: nds.common.NdsResult result = 1
     */
    result?: NdsResult;
    /**
     * Events (valid only on success).
     *
     * @generated from protobuf field: repeated nds.event.NdsEvent events = 2
     */
    events: NdsEvent[];
    /**
     * Total count (for pagination).
     *
     * @generated from protobuf field: int64 total_count = 3
     */
    totalCount: string;
}
/**
 * [Index] NDS-PROTO-QUERY-150 QueryProjectionRequest
 *
 * @generated from protobuf message nds.query.QueryProjectionRequest
 */
export interface QueryProjectionRequest {
    /**
     * Projection ID.
     *
     * @generated from protobuf field: nds.projection.ProjectionId projection_id = 1
     */
    projectionId?: ProjectionId;
    /**
     * Context (optional).
     *
     * @generated from protobuf field: optional nds.context.NdsContext context = 2
     */
    context?: NdsContext;
}
/**
 * [Index] NDS-PROTO-QUERY-160 QueryProjectionResponse
 *
 * @generated from protobuf message nds.query.QueryProjectionResponse
 */
export interface QueryProjectionResponse {
    /**
     * Result.
     *
     * @generated from protobuf field: nds.common.NdsResult result = 1
     */
    result?: NdsResult;
    /**
     * Projection (valid only on success).
     *
     * @generated from protobuf field: optional nds.projection.NdsProjection projection = 2
     */
    projection?: NdsProjection;
}
/**
 * [Index] NDS-PROTO-QUERY-170 ReplayRequest
 *
 * @generated from protobuf message nds.query.ReplayRequest
 */
export interface ReplayRequest {
    /**
     * Projection ID.
     *
     * @generated from protobuf field: nds.projection.ProjectionId projection_id = 1
     */
    projectionId?: ProjectionId;
    /**
     * Target time.
     *
     * @generated from protobuf field: google.protobuf.Timestamp target_time = 2
     */
    targetTime?: Timestamp;
    /**
     * Context (optional).
     *
     * @generated from protobuf field: optional nds.context.NdsContext context = 3
     */
    context?: NdsContext;
}
/**
 * [Index] NDS-PROTO-QUERY-180 ReplayResponse
 *
 * @generated from protobuf message nds.query.ReplayResponse
 */
export interface ReplayResponse {
    /**
     * Result.
     *
     * @generated from protobuf field: nds.common.NdsResult result = 1
     */
    result?: NdsResult;
    /**
     * Projection after replay (valid only on success).
     *
     * @generated from protobuf field: optional nds.projection.NdsProjection projection = 2
     */
    projection?: NdsProjection;
}
/**
 * [Index] NDS-PROTO-QUERY-190 RegisterProjectionRequest
 *
 * @generated from protobuf message nds.query.RegisterProjectionRequest
 */
export interface RegisterProjectionRequest {
    /**
     * Projection ID.
     *
     * @generated from protobuf field: nds.projection.ProjectionId projection_id = 1
     */
    projectionId?: ProjectionId;
    /**
     * Projection config (JSON).
     *
     * @generated from protobuf field: string config = 2
     */
    config: string;
    /**
     * Context (optional).
     *
     * @generated from protobuf field: optional nds.context.NdsContext context = 3
     */
    context?: NdsContext;
}
/**
 * [Index] NDS-PROTO-QUERY-200 RegisterProjectionResponse
 *
 * @generated from protobuf message nds.query.RegisterProjectionResponse
 */
export interface RegisterProjectionResponse {
    /**
     * Result.
     *
     * @generated from protobuf field: nds.common.NdsResult result = 1
     */
    result?: NdsResult;
}
/**
 * [Index] NDS-PROTO-QUERY-210 UnregisterProjectionRequest
 *
 * @generated from protobuf message nds.query.UnregisterProjectionRequest
 */
export interface UnregisterProjectionRequest {
    /**
     * Projection ID.
     *
     * @generated from protobuf field: nds.projection.ProjectionId projection_id = 1
     */
    projectionId?: ProjectionId;
    /**
     * Context (optional).
     *
     * @generated from protobuf field: optional nds.context.NdsContext context = 2
     */
    context?: NdsContext;
}
/**
 * [Index] NDS-PROTO-QUERY-220 UnregisterProjectionResponse
 *
 * @generated from protobuf message nds.query.UnregisterProjectionResponse
 */
export interface UnregisterProjectionResponse {
    /**
     * Result.
     *
     * @generated from protobuf field: nds.common.NdsResult result = 1
     */
    result?: NdsResult;
}
// @generated message type with reflection information, may provide speed optimized methods
class QueryBalanceRequest$Type extends MessageType<QueryBalanceRequest> {
    constructor() {
        super("nds.query.QueryBalanceRequest", [
            { no: 1, name: "asset", kind: "message", T: () => AssetId },
            { no: 2, name: "identity", kind: "message", T: () => NdsIdentity },
            { no: 3, name: "context", kind: "message", T: () => NdsContext }
        ]);
    }
    create(value?: PartialMessage<QueryBalanceRequest>): QueryBalanceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<QueryBalanceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryBalanceRequest): QueryBalanceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.asset.AssetId asset */ 1:
                    message.asset = AssetId.internalBinaryRead(reader, reader.uint32(), options, message.asset);
                    break;
                case /* optional nds.identity.NdsIdentity identity */ 2:
                    message.identity = NdsIdentity.internalBinaryRead(reader, reader.uint32(), options, message.identity);
                    break;
                case /* optional nds.context.NdsContext context */ 3:
                    message.context = NdsContext.internalBinaryRead(reader, reader.uint32(), options, message.context);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QueryBalanceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.asset.AssetId asset = 1; */
        if (message.asset)
            AssetId.internalBinaryWrite(message.asset, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.identity.NdsIdentity identity = 2; */
        if (message.identity)
            NdsIdentity.internalBinaryWrite(message.identity, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.context.NdsContext context = 3; */
        if (message.context)
            NdsContext.internalBinaryWrite(message.context, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.QueryBalanceRequest
 */
export const QueryBalanceRequest = new QueryBalanceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QueryBalanceResponse$Type extends MessageType<QueryBalanceResponse> {
    constructor() {
        super("nds.query.QueryBalanceResponse", [
            { no: 1, name: "result", kind: "message", T: () => NdsResult },
            { no: 2, name: "balance", kind: "message", T: () => Decimal }
        ]);
    }
    create(value?: PartialMessage<QueryBalanceResponse>): QueryBalanceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<QueryBalanceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryBalanceResponse): QueryBalanceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.common.NdsResult result */ 1:
                    message.result = NdsResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                case /* optional nds.common.Decimal balance */ 2:
                    message.balance = Decimal.internalBinaryRead(reader, reader.uint32(), options, message.balance);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QueryBalanceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.common.NdsResult result = 1; */
        if (message.result)
            NdsResult.internalBinaryWrite(message.result, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.common.Decimal balance = 2; */
        if (message.balance)
            Decimal.internalBinaryWrite(message.balance, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.QueryBalanceResponse
 */
export const QueryBalanceResponse = new QueryBalanceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QueryHistoryRequest$Type extends MessageType<QueryHistoryRequest> {
    constructor() {
        super("nds.query.QueryHistoryRequest", [
            { no: 1, name: "asset", kind: "message", T: () => AssetId },
            { no: 2, name: "identity", kind: "message", T: () => NdsIdentity },
            { no: 3, name: "start_time", kind: "message", T: () => Timestamp },
            { no: 4, name: "end_time", kind: "message", T: () => Timestamp },
            { no: 5, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "context", kind: "message", T: () => NdsContext }
        ]);
    }
    create(value?: PartialMessage<QueryHistoryRequest>): QueryHistoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.limit = 0;
        message.offset = 0;
        if (value !== undefined)
            reflectionMergePartial<QueryHistoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryHistoryRequest): QueryHistoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional nds.asset.AssetId asset */ 1:
                    message.asset = AssetId.internalBinaryRead(reader, reader.uint32(), options, message.asset);
                    break;
                case /* optional nds.identity.NdsIdentity identity */ 2:
                    message.identity = NdsIdentity.internalBinaryRead(reader, reader.uint32(), options, message.identity);
                    break;
                case /* optional google.protobuf.Timestamp start_time */ 3:
                    message.startTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.startTime);
                    break;
                case /* optional google.protobuf.Timestamp end_time */ 4:
                    message.endTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.endTime);
                    break;
                case /* int32 limit */ 5:
                    message.limit = reader.int32();
                    break;
                case /* int32 offset */ 6:
                    message.offset = reader.int32();
                    break;
                case /* optional nds.context.NdsContext context */ 7:
                    message.context = NdsContext.internalBinaryRead(reader, reader.uint32(), options, message.context);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QueryHistoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional nds.asset.AssetId asset = 1; */
        if (message.asset)
            AssetId.internalBinaryWrite(message.asset, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.identity.NdsIdentity identity = 2; */
        if (message.identity)
            NdsIdentity.internalBinaryWrite(message.identity, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Timestamp start_time = 3; */
        if (message.startTime)
            Timestamp.internalBinaryWrite(message.startTime, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Timestamp end_time = 4; */
        if (message.endTime)
            Timestamp.internalBinaryWrite(message.endTime, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* int32 limit = 5; */
        if (message.limit !== 0)
            writer.tag(5, WireType.Varint).int32(message.limit);
        /* int32 offset = 6; */
        if (message.offset !== 0)
            writer.tag(6, WireType.Varint).int32(message.offset);
        /* optional nds.context.NdsContext context = 7; */
        if (message.context)
            NdsContext.internalBinaryWrite(message.context, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.QueryHistoryRequest
 */
export const QueryHistoryRequest = new QueryHistoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QueryHistoryResponse$Type extends MessageType<QueryHistoryResponse> {
    constructor() {
        super("nds.query.QueryHistoryResponse", [
            { no: 1, name: "result", kind: "message", T: () => NdsResult },
            { no: 2, name: "events", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => NdsEvent },
            { no: 3, name: "total_count", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<QueryHistoryResponse>): QueryHistoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.events = [];
        message.totalCount = "0";
        if (value !== undefined)
            reflectionMergePartial<QueryHistoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryHistoryResponse): QueryHistoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.common.NdsResult result */ 1:
                    message.result = NdsResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                case /* repeated nds.event.NdsEvent events */ 2:
                    message.events.push(NdsEvent.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int64 total_count */ 3:
                    message.totalCount = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QueryHistoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.common.NdsResult result = 1; */
        if (message.result)
            NdsResult.internalBinaryWrite(message.result, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated nds.event.NdsEvent events = 2; */
        for (let i = 0; i < message.events.length; i++)
            NdsEvent.internalBinaryWrite(message.events[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* int64 total_count = 3; */
        if (message.totalCount !== "0")
            writer.tag(3, WireType.Varint).int64(message.totalCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.QueryHistoryResponse
 */
export const QueryHistoryResponse = new QueryHistoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QueryProjectionRequest$Type extends MessageType<QueryProjectionRequest> {
    constructor() {
        super("nds.query.QueryProjectionRequest", [
            { no: 1, name: "projection_id", kind: "message", T: () => ProjectionId },
            { no: 2, name: "context", kind: "message", T: () => NdsContext }
        ]);
    }
    create(value?: PartialMessage<QueryProjectionRequest>): QueryProjectionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<QueryProjectionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryProjectionRequest): QueryProjectionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.projection.ProjectionId projection_id */ 1:
                    message.projectionId = ProjectionId.internalBinaryRead(reader, reader.uint32(), options, message.projectionId);
                    break;
                case /* optional nds.context.NdsContext context */ 2:
                    message.context = NdsContext.internalBinaryRead(reader, reader.uint32(), options, message.context);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QueryProjectionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.projection.ProjectionId projection_id = 1; */
        if (message.projectionId)
            ProjectionId.internalBinaryWrite(message.projectionId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.context.NdsContext context = 2; */
        if (message.context)
            NdsContext.internalBinaryWrite(message.context, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.QueryProjectionRequest
 */
export const QueryProjectionRequest = new QueryProjectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QueryProjectionResponse$Type extends MessageType<QueryProjectionResponse> {
    constructor() {
        super("nds.query.QueryProjectionResponse", [
            { no: 1, name: "result", kind: "message", T: () => NdsResult },
            { no: 2, name: "projection", kind: "message", T: () => NdsProjection }
        ]);
    }
    create(value?: PartialMessage<QueryProjectionResponse>): QueryProjectionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<QueryProjectionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryProjectionResponse): QueryProjectionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.common.NdsResult result */ 1:
                    message.result = NdsResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                case /* optional nds.projection.NdsProjection projection */ 2:
                    message.projection = NdsProjection.internalBinaryRead(reader, reader.uint32(), options, message.projection);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QueryProjectionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.common.NdsResult result = 1; */
        if (message.result)
            NdsResult.internalBinaryWrite(message.result, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.projection.NdsProjection projection = 2; */
        if (message.projection)
            NdsProjection.internalBinaryWrite(message.projection, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.QueryProjectionResponse
 */
export const QueryProjectionResponse = new QueryProjectionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReplayRequest$Type extends MessageType<ReplayRequest> {
    constructor() {
        super("nds.query.ReplayRequest", [
            { no: 1, name: "projection_id", kind: "message", T: () => ProjectionId },
            { no: 2, name: "target_time", kind: "message", T: () => Timestamp },
            { no: 3, name: "context", kind: "message", T: () => NdsContext }
        ]);
    }
    create(value?: PartialMessage<ReplayRequest>): ReplayRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReplayRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReplayRequest): ReplayRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.projection.ProjectionId projection_id */ 1:
                    message.projectionId = ProjectionId.internalBinaryRead(reader, reader.uint32(), options, message.projectionId);
                    break;
                case /* google.protobuf.Timestamp target_time */ 2:
                    message.targetTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.targetTime);
                    break;
                case /* optional nds.context.NdsContext context */ 3:
                    message.context = NdsContext.internalBinaryRead(reader, reader.uint32(), options, message.context);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReplayRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.projection.ProjectionId projection_id = 1; */
        if (message.projectionId)
            ProjectionId.internalBinaryWrite(message.projectionId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp target_time = 2; */
        if (message.targetTime)
            Timestamp.internalBinaryWrite(message.targetTime, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.context.NdsContext context = 3; */
        if (message.context)
            NdsContext.internalBinaryWrite(message.context, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.ReplayRequest
 */
export const ReplayRequest = new ReplayRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReplayResponse$Type extends MessageType<ReplayResponse> {
    constructor() {
        super("nds.query.ReplayResponse", [
            { no: 1, name: "result", kind: "message", T: () => NdsResult },
            { no: 2, name: "projection", kind: "message", T: () => NdsProjection }
        ]);
    }
    create(value?: PartialMessage<ReplayResponse>): ReplayResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReplayResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReplayResponse): ReplayResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.common.NdsResult result */ 1:
                    message.result = NdsResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                case /* optional nds.projection.NdsProjection projection */ 2:
                    message.projection = NdsProjection.internalBinaryRead(reader, reader.uint32(), options, message.projection);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReplayResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.common.NdsResult result = 1; */
        if (message.result)
            NdsResult.internalBinaryWrite(message.result, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.projection.NdsProjection projection = 2; */
        if (message.projection)
            NdsProjection.internalBinaryWrite(message.projection, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.ReplayResponse
 */
export const ReplayResponse = new ReplayResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterProjectionRequest$Type extends MessageType<RegisterProjectionRequest> {
    constructor() {
        super("nds.query.RegisterProjectionRequest", [
            { no: 1, name: "projection_id", kind: "message", T: () => ProjectionId },
            { no: 2, name: "config", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "context", kind: "message", T: () => NdsContext }
        ]);
    }
    create(value?: PartialMessage<RegisterProjectionRequest>): RegisterProjectionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.config = "";
        if (value !== undefined)
            reflectionMergePartial<RegisterProjectionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterProjectionRequest): RegisterProjectionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.projection.ProjectionId projection_id */ 1:
                    message.projectionId = ProjectionId.internalBinaryRead(reader, reader.uint32(), options, message.projectionId);
                    break;
                case /* string config */ 2:
                    message.config = reader.string();
                    break;
                case /* optional nds.context.NdsContext context */ 3:
                    message.context = NdsContext.internalBinaryRead(reader, reader.uint32(), options, message.context);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterProjectionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.projection.ProjectionId projection_id = 1; */
        if (message.projectionId)
            ProjectionId.internalBinaryWrite(message.projectionId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string config = 2; */
        if (message.config !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.config);
        /* optional nds.context.NdsContext context = 3; */
        if (message.context)
            NdsContext.internalBinaryWrite(message.context, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.RegisterProjectionRequest
 */
export const RegisterProjectionRequest = new RegisterProjectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterProjectionResponse$Type extends MessageType<RegisterProjectionResponse> {
    constructor() {
        super("nds.query.RegisterProjectionResponse", [
            { no: 1, name: "result", kind: "message", T: () => NdsResult }
        ]);
    }
    create(value?: PartialMessage<RegisterProjectionResponse>): RegisterProjectionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RegisterProjectionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterProjectionResponse): RegisterProjectionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.common.NdsResult result */ 1:
                    message.result = NdsResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterProjectionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.common.NdsResult result = 1; */
        if (message.result)
            NdsResult.internalBinaryWrite(message.result, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.RegisterProjectionResponse
 */
export const RegisterProjectionResponse = new RegisterProjectionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnregisterProjectionRequest$Type extends MessageType<UnregisterProjectionRequest> {
    constructor() {
        super("nds.query.UnregisterProjectionRequest", [
            { no: 1, name: "projection_id", kind: "message", T: () => ProjectionId },
            { no: 2, name: "context", kind: "message", T: () => NdsContext }
        ]);
    }
    create(value?: PartialMessage<UnregisterProjectionRequest>): UnregisterProjectionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UnregisterProjectionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UnregisterProjectionRequest): UnregisterProjectionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.projection.ProjectionId projection_id */ 1:
                    message.projectionId = ProjectionId.internalBinaryRead(reader, reader.uint32(), options, message.projectionId);
                    break;
                case /* optional nds.context.NdsContext context */ 2:
                    message.context = NdsContext.internalBinaryRead(reader, reader.uint32(), options, message.context);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UnregisterProjectionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.projection.ProjectionId projection_id = 1; */
        if (message.projectionId)
            ProjectionId.internalBinaryWrite(message.projectionId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional nds.context.NdsContext context = 2; */
        if (message.context)
            NdsContext.internalBinaryWrite(message.context, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.UnregisterProjectionRequest
 */
export const UnregisterProjectionRequest = new UnregisterProjectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnregisterProjectionResponse$Type extends MessageType<UnregisterProjectionResponse> {
    constructor() {
        super("nds.query.UnregisterProjectionResponse", [
            { no: 1, name: "result", kind: "message", T: () => NdsResult }
        ]);
    }
    create(value?: PartialMessage<UnregisterProjectionResponse>): UnregisterProjectionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UnregisterProjectionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UnregisterProjectionResponse): UnregisterProjectionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nds.common.NdsResult result */ 1:
                    message.result = NdsResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UnregisterProjectionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nds.common.NdsResult result = 1; */
        if (message.result)
            NdsResult.internalBinaryWrite(message.result, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.query.UnregisterProjectionResponse
 */
export const UnregisterProjectionResponse = new UnregisterProjectionResponse$Type();
/**
 * @generated ServiceType for protobuf service nds.query.NdsQueryService
 */
export const NdsQueryService = new ServiceType("nds.query.NdsQueryService", [
    { name: "QueryBalance", options: {}, I: QueryBalanceRequest, O: QueryBalanceResponse },
    { name: "QueryHistory", options: {}, I: QueryHistoryRequest, O: QueryHistoryResponse },
    { name: "QueryProjection", options: {}, I: QueryProjectionRequest, O: QueryProjectionResponse },
    { name: "Replay", options: {}, I: ReplayRequest, O: ReplayResponse },
    { name: "RegisterProjection", options: {}, I: RegisterProjectionRequest, O: RegisterProjectionResponse },
    { name: "UnregisterProjection", options: {}, I: UnregisterProjectionRequest, O: UnregisterProjectionResponse }
]);
