# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nds/policy/policy.proto

require 'google/protobuf'


descriptor_data = "\n\x17nds/policy/policy.proto\x12\nnds.policy\"\xe2\x02\n\tNdsPolicy\x12\x1b\n\tpolicy_id\x18\x01 \x01(\tR\x08policyId\x12\x1f\n\x0bpolicy_type\x18\x02 \x01(\tR\npolicyType\x12\x39\n\x06params\x18\x03 \x03(\x0b\x32!.nds.policy.NdsPolicy.ParamsEntryR\x06params\x12#\n\rcustom_config\x18\x04 \x01(\x0cR\x0c\x63ustomConfig\x12?\n\x08metadata\x18\x05 \x03(\x0b\x32#.nds.policy.NdsPolicy.MetadataEntryR\x08metadata\x1a\x39\n\x0bParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\xb9\x01\n5noie.linmimeng.noiedigitalsystem.api.proto.nds.policyB\x0bPolicyProtoP\x01Z*github.com/misty4119/nds-api/Go/nds/policy\xa2\x02\x03NPX\xaa\x02\nNds.Policy\xca\x02\nNds\\Policy\xe2\x02\x16Nds\\Policy\\GPBMetadata\xea\x02\x0bNds::Policyb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Nds
  module Policy
    NdsPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nds.policy.NdsPolicy").msgclass
  end
end
