// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nds/context/context.proto
// Protobuf C++ Version: 6.33.5

#ifndef nds_2fcontext_2fcontext_2eproto_2epb_2eh
#define nds_2fcontext_2fcontext_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_nds_2fcontext_2fcontext_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_nds_2fcontext_2fcontext_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_nds_2fcontext_2fcontext_2eproto;
}  // extern "C"
namespace nds {
namespace context {
class NdsContext;
struct NdsContextDefaultTypeInternal;
extern NdsContextDefaultTypeInternal _NdsContext_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NdsContext_class_data_;
class NdsContext_MetaEntry_DoNotUse;
struct NdsContext_MetaEntry_DoNotUseDefaultTypeInternal;
extern NdsContext_MetaEntry_DoNotUseDefaultTypeInternal _NdsContext_MetaEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NdsContext_MetaEntry_DoNotUse_class_data_;
}  // namespace context
}  // namespace nds
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace nds {
namespace context {

// ===================================================================


// -------------------------------------------------------------------

class NdsContext_MetaEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  NdsContext_MetaEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NdsContext_MetaEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit NdsContext_MetaEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_NdsContext_MetaEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_nds_2fcontext_2fcontext_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 49,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull NdsContext_MetaEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class NdsContext final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nds.context.NdsContext) */ {
 public:
  inline NdsContext() : NdsContext(nullptr) {}
  ~NdsContext() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NdsContext* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NdsContext));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NdsContext(::google::protobuf::internal::ConstantInitialized);

  inline NdsContext(const NdsContext& from) : NdsContext(nullptr, from) {}
  inline NdsContext(NdsContext&& from) noexcept
      : NdsContext(nullptr, ::std::move(from)) {}
  inline NdsContext& operator=(const NdsContext& from) {
    CopyFrom(from);
    return *this;
  }
  inline NdsContext& operator=(NdsContext&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NdsContext& default_instance() {
    return *reinterpret_cast<const NdsContext*>(
        &_NdsContext_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(NdsContext& a, NdsContext& b) { a.Swap(&b); }
  inline void Swap(NdsContext* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NdsContext* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NdsContext* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NdsContext>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NdsContext& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NdsContext& from) { NdsContext::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NdsContext* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nds.context.NdsContext"; }

  explicit NdsContext(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NdsContext(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NdsContext& from);
  NdsContext(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NdsContext&& from) noexcept
      : NdsContext(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTraceIdFieldNumber = 1,
    kCorrelationIdFieldNumber = 2,
    kSpanIdFieldNumber = 3,
    kParentSpanIdFieldNumber = 4,
    kTimestampFieldNumber = 6,
    kMetaFieldNumber = 5,
  };
  // string trace_id = 1 [json_name = "traceId"];
  void clear_trace_id() ;
  const ::std::string& trace_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_trace_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_trace_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_trace_id();
  void set_allocated_trace_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_trace_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_trace_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_trace_id();

  public:
  // string correlation_id = 2 [json_name = "correlationId"];
  void clear_correlation_id() ;
  const ::std::string& correlation_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_correlation_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_correlation_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_correlation_id();
  void set_allocated_correlation_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_correlation_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_correlation_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_correlation_id();

  public:
  // optional string span_id = 3 [json_name = "spanId"];
  bool has_span_id() const;
  void clear_span_id() ;
  const ::std::string& span_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_span_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_span_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_span_id();
  void set_allocated_span_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_span_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_span_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_span_id();

  public:
  // optional string parent_span_id = 4 [json_name = "parentSpanId"];
  bool has_parent_span_id() const;
  void clear_parent_span_id() ;
  const ::std::string& parent_span_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_parent_span_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_parent_span_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_parent_span_id();
  void set_allocated_parent_span_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_parent_span_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_parent_span_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_parent_span_id();

  public:
  // int64 timestamp = 6 [json_name = "timestamp"];
  void clear_timestamp() ;
  ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // map<string, string> meta = 5 [json_name = "meta"];
  int meta_size() const;
  private:
  int _internal_meta_size() const;

  public:
  void clear_meta() ;
  const ::google::protobuf::Map<::std::string, ::std::string>& meta() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_meta();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_meta() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_meta();

  public:
  // @@protoc_insertion_point(class_scope:nds.context.NdsContext)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   1, 78,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NdsContext& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr trace_id_;
    ::google::protobuf::internal::ArenaStringPtr correlation_id_;
    ::google::protobuf::internal::ArenaStringPtr span_id_;
    ::google::protobuf::internal::ArenaStringPtr parent_span_id_;
    ::int64_t timestamp_;
    ::google::protobuf::internal::MapField<NdsContext_MetaEntry_DoNotUse, ::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        meta_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nds_2fcontext_2fcontext_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NdsContext_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// NdsContext

// string trace_id = 1 [json_name = "traceId"];
inline void NdsContext::clear_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& NdsContext::trace_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.context.NdsContext.trace_id)
  return _internal_trace_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NdsContext::set_trace_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.trace_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.context.NdsContext.trace_id)
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::mutable_trace_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_trace_id();
  // @@protoc_insertion_point(field_mutable:nds.context.NdsContext.trace_id)
  return _s;
}
inline const ::std::string& NdsContext::_internal_trace_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.trace_id_.Get();
}
inline void NdsContext::_internal_set_trace_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trace_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::_internal_mutable_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.trace_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NdsContext::release_trace_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.context.NdsContext.trace_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.trace_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.trace_id_.Set("", GetArena());
  }
  return released;
}
inline void NdsContext::set_allocated_trace_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.trace_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.trace_id_.IsDefault()) {
    _impl_.trace_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.context.NdsContext.trace_id)
}

// string correlation_id = 2 [json_name = "correlationId"];
inline void NdsContext::clear_correlation_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.correlation_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& NdsContext::correlation_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.context.NdsContext.correlation_id)
  return _internal_correlation_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NdsContext::set_correlation_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.correlation_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.context.NdsContext.correlation_id)
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::mutable_correlation_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_correlation_id();
  // @@protoc_insertion_point(field_mutable:nds.context.NdsContext.correlation_id)
  return _s;
}
inline const ::std::string& NdsContext::_internal_correlation_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.correlation_id_.Get();
}
inline void NdsContext::_internal_set_correlation_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.correlation_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::_internal_mutable_correlation_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.correlation_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NdsContext::release_correlation_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.context.NdsContext.correlation_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.correlation_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.correlation_id_.Set("", GetArena());
  }
  return released;
}
inline void NdsContext::set_allocated_correlation_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.correlation_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.correlation_id_.IsDefault()) {
    _impl_.correlation_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.context.NdsContext.correlation_id)
}

// optional string span_id = 3 [json_name = "spanId"];
inline bool NdsContext::has_span_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void NdsContext::clear_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.span_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& NdsContext::span_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.context.NdsContext.span_id)
  return _internal_span_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NdsContext::set_span_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.span_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.context.NdsContext.span_id)
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::mutable_span_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_span_id();
  // @@protoc_insertion_point(field_mutable:nds.context.NdsContext.span_id)
  return _s;
}
inline const ::std::string& NdsContext::_internal_span_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.span_id_.Get();
}
inline void NdsContext::_internal_set_span_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.span_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::_internal_mutable_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.span_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NdsContext::release_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.context.NdsContext.span_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.span_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.span_id_.Set("", GetArena());
  }
  return released;
}
inline void NdsContext::set_allocated_span_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.span_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.span_id_.IsDefault()) {
    _impl_.span_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.context.NdsContext.span_id)
}

// optional string parent_span_id = 4 [json_name = "parentSpanId"];
inline bool NdsContext::has_parent_span_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void NdsContext::clear_parent_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_span_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& NdsContext::parent_span_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.context.NdsContext.parent_span_id)
  return _internal_parent_span_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NdsContext::set_parent_span_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.parent_span_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.context.NdsContext.parent_span_id)
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::mutable_parent_span_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_parent_span_id();
  // @@protoc_insertion_point(field_mutable:nds.context.NdsContext.parent_span_id)
  return _s;
}
inline const ::std::string& NdsContext::_internal_parent_span_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parent_span_id_.Get();
}
inline void NdsContext::_internal_set_parent_span_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_span_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NdsContext::_internal_mutable_parent_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.parent_span_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NdsContext::release_parent_span_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.context.NdsContext.parent_span_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.parent_span_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.parent_span_id_.Set("", GetArena());
  }
  return released;
}
inline void NdsContext::set_allocated_parent_span_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.parent_span_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.parent_span_id_.IsDefault()) {
    _impl_.parent_span_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.context.NdsContext.parent_span_id)
}

// map<string, string> meta = 5 [json_name = "meta"];
inline int NdsContext::_internal_meta_size() const {
  return _internal_meta().size();
}
inline int NdsContext::meta_size() const {
  return _internal_meta_size();
}
inline void NdsContext::clear_meta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.meta_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& NdsContext::_internal_meta() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.meta_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& NdsContext::meta() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:nds.context.NdsContext.meta)
  return _internal_meta();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL NdsContext::_internal_mutable_meta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.meta_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL NdsContext::mutable_meta()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_mutable_map:nds.context.NdsContext.meta)
  return _internal_mutable_meta();
}

// int64 timestamp = 6 [json_name = "timestamp"];
inline void NdsContext::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int64_t NdsContext::timestamp() const {
  // @@protoc_insertion_point(field_get:nds.context.NdsContext.timestamp)
  return _internal_timestamp();
}
inline void NdsContext::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:nds.context.NdsContext.timestamp)
}
inline ::int64_t NdsContext::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void NdsContext::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace context
}  // namespace nds


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // nds_2fcontext_2fcontext_2eproto_2epb_2eh
