// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nds/memory/v1/memory.proto
// Protobuf C++ Version: 6.33.5

#ifndef nds_2fmemory_2fv1_2fmemory_2eproto_2epb_2eh
#define nds_2fmemory_2fv1_2fmemory_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "nds/identity/v1/identity_v1.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_nds_2fmemory_2fv1_2fmemory_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_nds_2fmemory_2fv1_2fmemory_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_nds_2fmemory_2fv1_2fmemory_2eproto;
}  // extern "C"
namespace nds {
namespace memory {
namespace v1 {
enum RedactionReason : int;
extern const uint32_t RedactionReason_internal_data_[];
class Hash;
struct HashDefaultTypeInternal;
extern HashDefaultTypeInternal _Hash_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Hash_class_data_;
class MemoryArtifact;
struct MemoryArtifactDefaultTypeInternal;
extern MemoryArtifactDefaultTypeInternal _MemoryArtifact_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MemoryArtifact_class_data_;
class MemoryProof;
struct MemoryProofDefaultTypeInternal;
extern MemoryProofDefaultTypeInternal _MemoryProof_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MemoryProof_class_data_;
}  // namespace v1
}  // namespace memory
}  // namespace nds
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::nds::memory::v1::RedactionReason_internal_data_>
    internal::EnumTraitsImpl::value<::nds::memory::v1::RedactionReason>;
}  // namespace protobuf
}  // namespace google

namespace nds {
namespace memory {
namespace v1 {
enum RedactionReason : int {
  REDACTION_REASON_UNSPECIFIED = 0,
  REDACTION_REASON_PRIVACY_REQUEST = 1,
  REDACTION_REASON_POLICY = 2,
  REDACTION_REASON_LEGAL = 3,
  RedactionReason_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RedactionReason_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RedactionReason_internal_data_[];
inline constexpr RedactionReason RedactionReason_MIN =
    static_cast<RedactionReason>(0);
inline constexpr RedactionReason RedactionReason_MAX =
    static_cast<RedactionReason>(3);
inline bool RedactionReason_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int RedactionReason_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RedactionReason_descriptor();
template <typename T>
const ::std::string& RedactionReason_Name(T value) {
  static_assert(::std::is_same<T, RedactionReason>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RedactionReason_Name().");
  return RedactionReason_Name(static_cast<RedactionReason>(value));
}
template <>
inline const ::std::string& RedactionReason_Name(RedactionReason value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RedactionReason_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool RedactionReason_Parse(
    ::absl::string_view name, RedactionReason* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RedactionReason>(RedactionReason_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Hash final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nds.memory.v1.Hash) */ {
 public:
  inline Hash() : Hash(nullptr) {}
  ~Hash() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Hash* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Hash));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Hash(::google::protobuf::internal::ConstantInitialized);

  inline Hash(const Hash& from) : Hash(nullptr, from) {}
  inline Hash(Hash&& from) noexcept
      : Hash(nullptr, ::std::move(from)) {}
  inline Hash& operator=(const Hash& from) {
    CopyFrom(from);
    return *this;
  }
  inline Hash& operator=(Hash&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Hash& default_instance() {
    return *reinterpret_cast<const Hash*>(
        &_Hash_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Hash& a, Hash& b) { a.Swap(&b); }
  inline void Swap(Hash* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Hash* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Hash* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Hash>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Hash& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Hash& from) { Hash::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Hash* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nds.memory.v1.Hash"; }

  explicit Hash(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Hash(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Hash& from);
  Hash(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Hash&& from) noexcept
      : Hash(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAlgorithmFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // string algorithm = 1 [json_name = "algorithm"];
  void clear_algorithm() ;
  const ::std::string& algorithm() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_algorithm(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_algorithm();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_algorithm();
  void set_allocated_algorithm(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_algorithm() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_algorithm(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_algorithm();

  public:
  // bytes value = 2 [json_name = "value"];
  void clear_value() ;
  const ::std::string& value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // @@protoc_insertion_point(class_scope:nds.memory.v1.Hash)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Hash& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr algorithm_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nds_2fmemory_2fv1_2fmemory_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Hash_class_data_;
// -------------------------------------------------------------------

class MemoryProof final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nds.memory.v1.MemoryProof) */ {
 public:
  inline MemoryProof() : MemoryProof(nullptr) {}
  ~MemoryProof() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MemoryProof* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MemoryProof));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MemoryProof(::google::protobuf::internal::ConstantInitialized);

  inline MemoryProof(const MemoryProof& from) : MemoryProof(nullptr, from) {}
  inline MemoryProof(MemoryProof&& from) noexcept
      : MemoryProof(nullptr, ::std::move(from)) {}
  inline MemoryProof& operator=(const MemoryProof& from) {
    CopyFrom(from);
    return *this;
  }
  inline MemoryProof& operator=(MemoryProof&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MemoryProof& default_instance() {
    return *reinterpret_cast<const MemoryProof*>(
        &_MemoryProof_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MemoryProof& a, MemoryProof& b) { a.Swap(&b); }
  inline void Swap(MemoryProof* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MemoryProof* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MemoryProof* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MemoryProof>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MemoryProof& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MemoryProof& from) { MemoryProof::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MemoryProof* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nds.memory.v1.MemoryProof"; }

  explicit MemoryProof(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MemoryProof(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MemoryProof& from);
  MemoryProof(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MemoryProof&& from) noexcept
      : MemoryProof(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kProofTxIdFieldNumber = 1,
    kProofEventIdFieldNumber = 2,
    kContentHashFieldNumber = 10,
    kPrevHashFieldNumber = 11,
    kMerkleRootFieldNumber = 12,
  };
  // optional bytes proof_tx_id = 1 [json_name = "proofTxId"];
  bool has_proof_tx_id() const;
  void clear_proof_tx_id() ;
  const ::std::string& proof_tx_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_proof_tx_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_proof_tx_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_proof_tx_id();
  void set_allocated_proof_tx_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_proof_tx_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_proof_tx_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_proof_tx_id();

  public:
  // optional bytes proof_event_id = 2 [json_name = "proofEventId"];
  bool has_proof_event_id() const;
  void clear_proof_event_id() ;
  const ::std::string& proof_event_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_proof_event_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_proof_event_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_proof_event_id();
  void set_allocated_proof_event_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_proof_event_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_proof_event_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_proof_event_id();

  public:
  // .nds.memory.v1.Hash content_hash = 10 [json_name = "contentHash"];
  bool has_content_hash() const;
  void clear_content_hash() ;
  const ::nds::memory::v1::Hash& content_hash() const;
  [[nodiscard]] ::nds::memory::v1::Hash* PROTOBUF_NULLABLE release_content_hash();
  ::nds::memory::v1::Hash* PROTOBUF_NONNULL mutable_content_hash();
  void set_allocated_content_hash(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_content_hash(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value);
  ::nds::memory::v1::Hash* PROTOBUF_NULLABLE unsafe_arena_release_content_hash();

  private:
  const ::nds::memory::v1::Hash& _internal_content_hash() const;
  ::nds::memory::v1::Hash* PROTOBUF_NONNULL _internal_mutable_content_hash();

  public:
  // optional .nds.memory.v1.Hash prev_hash = 11 [json_name = "prevHash"];
  bool has_prev_hash() const;
  void clear_prev_hash() ;
  const ::nds::memory::v1::Hash& prev_hash() const;
  [[nodiscard]] ::nds::memory::v1::Hash* PROTOBUF_NULLABLE release_prev_hash();
  ::nds::memory::v1::Hash* PROTOBUF_NONNULL mutable_prev_hash();
  void set_allocated_prev_hash(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_prev_hash(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value);
  ::nds::memory::v1::Hash* PROTOBUF_NULLABLE unsafe_arena_release_prev_hash();

  private:
  const ::nds::memory::v1::Hash& _internal_prev_hash() const;
  ::nds::memory::v1::Hash* PROTOBUF_NONNULL _internal_mutable_prev_hash();

  public:
  // optional .nds.memory.v1.Hash merkle_root = 12 [json_name = "merkleRoot"];
  bool has_merkle_root() const;
  void clear_merkle_root() ;
  const ::nds::memory::v1::Hash& merkle_root() const;
  [[nodiscard]] ::nds::memory::v1::Hash* PROTOBUF_NULLABLE release_merkle_root();
  ::nds::memory::v1::Hash* PROTOBUF_NONNULL mutable_merkle_root();
  void set_allocated_merkle_root(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_merkle_root(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value);
  ::nds::memory::v1::Hash* PROTOBUF_NULLABLE unsafe_arena_release_merkle_root();

  private:
  const ::nds::memory::v1::Hash& _internal_merkle_root() const;
  ::nds::memory::v1::Hash* PROTOBUF_NONNULL _internal_mutable_merkle_root();

  public:
  // @@protoc_insertion_point(class_scope:nds.memory.v1.MemoryProof)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 5,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MemoryProof& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr proof_tx_id_;
    ::google::protobuf::internal::ArenaStringPtr proof_event_id_;
    ::nds::memory::v1::Hash* PROTOBUF_NULLABLE content_hash_;
    ::nds::memory::v1::Hash* PROTOBUF_NULLABLE prev_hash_;
    ::nds::memory::v1::Hash* PROTOBUF_NULLABLE merkle_root_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nds_2fmemory_2fv1_2fmemory_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MemoryProof_class_data_;
// -------------------------------------------------------------------

class MemoryArtifact final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nds.memory.v1.MemoryArtifact) */ {
 public:
  inline MemoryArtifact() : MemoryArtifact(nullptr) {}
  ~MemoryArtifact() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MemoryArtifact* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MemoryArtifact));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MemoryArtifact(::google::protobuf::internal::ConstantInitialized);

  inline MemoryArtifact(const MemoryArtifact& from) : MemoryArtifact(nullptr, from) {}
  inline MemoryArtifact(MemoryArtifact&& from) noexcept
      : MemoryArtifact(nullptr, ::std::move(from)) {}
  inline MemoryArtifact& operator=(const MemoryArtifact& from) {
    CopyFrom(from);
    return *this;
  }
  inline MemoryArtifact& operator=(MemoryArtifact&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MemoryArtifact& default_instance() {
    return *reinterpret_cast<const MemoryArtifact*>(
        &_MemoryArtifact_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MemoryArtifact& a, MemoryArtifact& b) { a.Swap(&b); }
  inline void Swap(MemoryArtifact* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MemoryArtifact* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MemoryArtifact* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MemoryArtifact>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MemoryArtifact& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MemoryArtifact& from) { MemoryArtifact::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MemoryArtifact* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nds.memory.v1.MemoryArtifact"; }

  explicit MemoryArtifact(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MemoryArtifact(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MemoryArtifact& from);
  MemoryArtifact(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MemoryArtifact&& from) noexcept
      : MemoryArtifact(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEmbeddingFieldNumber = 11,
    kIdFieldNumber = 1,
    kNarrativeFieldNumber = 10,
    kOwnerFieldNumber = 2,
    kProofFieldNumber = 20,
    kSchemaVersionFieldNumber = 3,
    kRedactedFieldNumber = 30,
    kRedactionReasonFieldNumber = 31,
  };
  // repeated float embedding = 11 [json_name = "embedding", packed = true];
  int embedding_size() const;
  private:
  int _internal_embedding_size() const;

  public:
  void clear_embedding() ;
  float embedding(int index) const;
  void set_embedding(int index, float value);
  void add_embedding(float value);
  const ::google::protobuf::RepeatedField<float>& embedding() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_embedding();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_embedding() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_embedding();

  public:
  // bytes id = 1 [json_name = "id"];
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // optional string narrative = 10 [json_name = "narrative"];
  bool has_narrative() const;
  void clear_narrative() ;
  const ::std::string& narrative() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_narrative(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_narrative();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_narrative();
  void set_allocated_narrative(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_narrative() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_narrative(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_narrative();

  public:
  // .nds.identity.v1.PersonaId owner = 2 [json_name = "owner"];
  bool has_owner() const;
  void clear_owner() ;
  const ::nds::identity::v1::PersonaId& owner() const;
  [[nodiscard]] ::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE release_owner();
  ::nds::identity::v1::PersonaId* PROTOBUF_NONNULL mutable_owner();
  void set_allocated_owner(::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_owner(::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE value);
  ::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE unsafe_arena_release_owner();

  private:
  const ::nds::identity::v1::PersonaId& _internal_owner() const;
  ::nds::identity::v1::PersonaId* PROTOBUF_NONNULL _internal_mutable_owner();

  public:
  // .nds.memory.v1.MemoryProof proof = 20 [json_name = "proof"];
  bool has_proof() const;
  void clear_proof() ;
  const ::nds::memory::v1::MemoryProof& proof() const;
  [[nodiscard]] ::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE release_proof();
  ::nds::memory::v1::MemoryProof* PROTOBUF_NONNULL mutable_proof();
  void set_allocated_proof(::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_proof(::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE value);
  ::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE unsafe_arena_release_proof();

  private:
  const ::nds::memory::v1::MemoryProof& _internal_proof() const;
  ::nds::memory::v1::MemoryProof* PROTOBUF_NONNULL _internal_mutable_proof();

  public:
  // int32 schema_version = 3 [json_name = "schemaVersion"];
  void clear_schema_version() ;
  ::int32_t schema_version() const;
  void set_schema_version(::int32_t value);

  private:
  ::int32_t _internal_schema_version() const;
  void _internal_set_schema_version(::int32_t value);

  public:
  // bool redacted = 30 [json_name = "redacted"];
  void clear_redacted() ;
  bool redacted() const;
  void set_redacted(bool value);

  private:
  bool _internal_redacted() const;
  void _internal_set_redacted(bool value);

  public:
  // optional .nds.memory.v1.RedactionReason redaction_reason = 31 [json_name = "redactionReason"];
  bool has_redaction_reason() const;
  void clear_redaction_reason() ;
  ::nds::memory::v1::RedactionReason redaction_reason() const;
  void set_redaction_reason(::nds::memory::v1::RedactionReason value);

  private:
  ::nds::memory::v1::RedactionReason _internal_redaction_reason() const;
  void _internal_set_redaction_reason(::nds::memory::v1::RedactionReason value);

  public:
  // @@protoc_insertion_point(class_scope:nds.memory.v1.MemoryArtifact)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 8,
                                   2, 54,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MemoryArtifact& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> embedding_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr narrative_;
    ::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE owner_;
    ::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE proof_;
    ::int32_t schema_version_;
    bool redacted_;
    int redaction_reason_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nds_2fmemory_2fv1_2fmemory_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MemoryArtifact_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Hash

// string algorithm = 1 [json_name = "algorithm"];
inline void Hash::clear_algorithm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.algorithm_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Hash::algorithm() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.Hash.algorithm)
  return _internal_algorithm();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Hash::set_algorithm(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.algorithm_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.memory.v1.Hash.algorithm)
}
inline ::std::string* PROTOBUF_NONNULL Hash::mutable_algorithm()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_algorithm();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.Hash.algorithm)
  return _s;
}
inline const ::std::string& Hash::_internal_algorithm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.algorithm_.Get();
}
inline void Hash::_internal_set_algorithm(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.algorithm_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Hash::_internal_mutable_algorithm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.algorithm_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Hash::release_algorithm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.Hash.algorithm)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.algorithm_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.algorithm_.Set("", GetArena());
  }
  return released;
}
inline void Hash::set_allocated_algorithm(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.algorithm_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.algorithm_.IsDefault()) {
    _impl_.algorithm_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.Hash.algorithm)
}

// bytes value = 2 [json_name = "value"];
inline void Hash::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Hash::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.Hash.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Hash::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.value_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.memory.v1.Hash.value)
}
inline ::std::string* PROTOBUF_NONNULL Hash::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.Hash.value)
  return _s;
}
inline const ::std::string& Hash::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void Hash::_internal_set_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Hash::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Hash::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.Hash.value)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void Hash::set_allocated_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.Hash.value)
}

// -------------------------------------------------------------------

// MemoryProof

// optional bytes proof_tx_id = 1 [json_name = "proofTxId"];
inline bool MemoryProof::has_proof_tx_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void MemoryProof::clear_proof_tx_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proof_tx_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& MemoryProof::proof_tx_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryProof.proof_tx_id)
  return _internal_proof_tx_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MemoryProof::set_proof_tx_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.proof_tx_id_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryProof.proof_tx_id)
}
inline ::std::string* PROTOBUF_NONNULL MemoryProof::mutable_proof_tx_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_proof_tx_id();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryProof.proof_tx_id)
  return _s;
}
inline const ::std::string& MemoryProof::_internal_proof_tx_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.proof_tx_id_.Get();
}
inline void MemoryProof::_internal_set_proof_tx_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proof_tx_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MemoryProof::_internal_mutable_proof_tx_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.proof_tx_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MemoryProof::release_proof_tx_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryProof.proof_tx_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.proof_tx_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.proof_tx_id_.Set("", GetArena());
  }
  return released;
}
inline void MemoryProof::set_allocated_proof_tx_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.proof_tx_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.proof_tx_id_.IsDefault()) {
    _impl_.proof_tx_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryProof.proof_tx_id)
}

// optional bytes proof_event_id = 2 [json_name = "proofEventId"];
inline bool MemoryProof::has_proof_event_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void MemoryProof::clear_proof_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proof_event_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& MemoryProof::proof_event_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryProof.proof_event_id)
  return _internal_proof_event_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MemoryProof::set_proof_event_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.proof_event_id_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryProof.proof_event_id)
}
inline ::std::string* PROTOBUF_NONNULL MemoryProof::mutable_proof_event_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_proof_event_id();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryProof.proof_event_id)
  return _s;
}
inline const ::std::string& MemoryProof::_internal_proof_event_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.proof_event_id_.Get();
}
inline void MemoryProof::_internal_set_proof_event_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proof_event_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MemoryProof::_internal_mutable_proof_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.proof_event_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MemoryProof::release_proof_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryProof.proof_event_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.proof_event_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.proof_event_id_.Set("", GetArena());
  }
  return released;
}
inline void MemoryProof::set_allocated_proof_event_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.proof_event_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.proof_event_id_.IsDefault()) {
    _impl_.proof_event_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryProof.proof_event_id)
}

// .nds.memory.v1.Hash content_hash = 10 [json_name = "contentHash"];
inline bool MemoryProof::has_content_hash() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.content_hash_ != nullptr);
  return value;
}
inline void MemoryProof::clear_content_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_hash_ != nullptr) _impl_.content_hash_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::nds::memory::v1::Hash& MemoryProof::_internal_content_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::nds::memory::v1::Hash* p = _impl_.content_hash_;
  return p != nullptr ? *p : reinterpret_cast<const ::nds::memory::v1::Hash&>(::nds::memory::v1::_Hash_default_instance_);
}
inline const ::nds::memory::v1::Hash& MemoryProof::content_hash() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryProof.content_hash)
  return _internal_content_hash();
}
inline void MemoryProof::unsafe_arena_set_allocated_content_hash(
    ::nds::memory::v1::Hash* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_hash_);
  }
  _impl_.content_hash_ = reinterpret_cast<::nds::memory::v1::Hash*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nds.memory.v1.MemoryProof.content_hash)
}
inline ::nds::memory::v1::Hash* PROTOBUF_NULLABLE MemoryProof::release_content_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::nds::memory::v1::Hash* released = _impl_.content_hash_;
  _impl_.content_hash_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NULLABLE MemoryProof::unsafe_arena_release_content_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryProof.content_hash)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::nds::memory::v1::Hash* temp = _impl_.content_hash_;
  _impl_.content_hash_ = nullptr;
  return temp;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NONNULL MemoryProof::_internal_mutable_content_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_hash_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::nds::memory::v1::Hash>(GetArena());
    _impl_.content_hash_ = reinterpret_cast<::nds::memory::v1::Hash*>(p);
  }
  return _impl_.content_hash_;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NONNULL MemoryProof::mutable_content_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::nds::memory::v1::Hash* _msg = _internal_mutable_content_hash();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryProof.content_hash)
  return _msg;
}
inline void MemoryProof::set_allocated_content_hash(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_hash_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.content_hash_ = reinterpret_cast<::nds::memory::v1::Hash*>(value);
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryProof.content_hash)
}

// optional .nds.memory.v1.Hash prev_hash = 11 [json_name = "prevHash"];
inline bool MemoryProof::has_prev_hash() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.prev_hash_ != nullptr);
  return value;
}
inline void MemoryProof::clear_prev_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.prev_hash_ != nullptr) _impl_.prev_hash_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::nds::memory::v1::Hash& MemoryProof::_internal_prev_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::nds::memory::v1::Hash* p = _impl_.prev_hash_;
  return p != nullptr ? *p : reinterpret_cast<const ::nds::memory::v1::Hash&>(::nds::memory::v1::_Hash_default_instance_);
}
inline const ::nds::memory::v1::Hash& MemoryProof::prev_hash() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryProof.prev_hash)
  return _internal_prev_hash();
}
inline void MemoryProof::unsafe_arena_set_allocated_prev_hash(
    ::nds::memory::v1::Hash* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.prev_hash_);
  }
  _impl_.prev_hash_ = reinterpret_cast<::nds::memory::v1::Hash*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nds.memory.v1.MemoryProof.prev_hash)
}
inline ::nds::memory::v1::Hash* PROTOBUF_NULLABLE MemoryProof::release_prev_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::nds::memory::v1::Hash* released = _impl_.prev_hash_;
  _impl_.prev_hash_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NULLABLE MemoryProof::unsafe_arena_release_prev_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryProof.prev_hash)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::nds::memory::v1::Hash* temp = _impl_.prev_hash_;
  _impl_.prev_hash_ = nullptr;
  return temp;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NONNULL MemoryProof::_internal_mutable_prev_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.prev_hash_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::nds::memory::v1::Hash>(GetArena());
    _impl_.prev_hash_ = reinterpret_cast<::nds::memory::v1::Hash*>(p);
  }
  return _impl_.prev_hash_;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NONNULL MemoryProof::mutable_prev_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::nds::memory::v1::Hash* _msg = _internal_mutable_prev_hash();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryProof.prev_hash)
  return _msg;
}
inline void MemoryProof::set_allocated_prev_hash(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.prev_hash_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.prev_hash_ = reinterpret_cast<::nds::memory::v1::Hash*>(value);
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryProof.prev_hash)
}

// optional .nds.memory.v1.Hash merkle_root = 12 [json_name = "merkleRoot"];
inline bool MemoryProof::has_merkle_root() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.merkle_root_ != nullptr);
  return value;
}
inline void MemoryProof::clear_merkle_root() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.merkle_root_ != nullptr) _impl_.merkle_root_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::nds::memory::v1::Hash& MemoryProof::_internal_merkle_root() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::nds::memory::v1::Hash* p = _impl_.merkle_root_;
  return p != nullptr ? *p : reinterpret_cast<const ::nds::memory::v1::Hash&>(::nds::memory::v1::_Hash_default_instance_);
}
inline const ::nds::memory::v1::Hash& MemoryProof::merkle_root() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryProof.merkle_root)
  return _internal_merkle_root();
}
inline void MemoryProof::unsafe_arena_set_allocated_merkle_root(
    ::nds::memory::v1::Hash* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.merkle_root_);
  }
  _impl_.merkle_root_ = reinterpret_cast<::nds::memory::v1::Hash*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nds.memory.v1.MemoryProof.merkle_root)
}
inline ::nds::memory::v1::Hash* PROTOBUF_NULLABLE MemoryProof::release_merkle_root() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::nds::memory::v1::Hash* released = _impl_.merkle_root_;
  _impl_.merkle_root_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NULLABLE MemoryProof::unsafe_arena_release_merkle_root() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryProof.merkle_root)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::nds::memory::v1::Hash* temp = _impl_.merkle_root_;
  _impl_.merkle_root_ = nullptr;
  return temp;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NONNULL MemoryProof::_internal_mutable_merkle_root() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.merkle_root_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::nds::memory::v1::Hash>(GetArena());
    _impl_.merkle_root_ = reinterpret_cast<::nds::memory::v1::Hash*>(p);
  }
  return _impl_.merkle_root_;
}
inline ::nds::memory::v1::Hash* PROTOBUF_NONNULL MemoryProof::mutable_merkle_root()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::nds::memory::v1::Hash* _msg = _internal_mutable_merkle_root();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryProof.merkle_root)
  return _msg;
}
inline void MemoryProof::set_allocated_merkle_root(::nds::memory::v1::Hash* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.merkle_root_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.merkle_root_ = reinterpret_cast<::nds::memory::v1::Hash*>(value);
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryProof.merkle_root)
}

// -------------------------------------------------------------------

// MemoryArtifact

// bytes id = 1 [json_name = "id"];
inline void MemoryArtifact::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& MemoryArtifact::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MemoryArtifact::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.id_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryArtifact.id)
}
inline ::std::string* PROTOBUF_NONNULL MemoryArtifact::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryArtifact.id)
  return _s;
}
inline const ::std::string& MemoryArtifact::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void MemoryArtifact::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MemoryArtifact::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MemoryArtifact::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryArtifact.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void MemoryArtifact::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryArtifact.id)
}

// .nds.identity.v1.PersonaId owner = 2 [json_name = "owner"];
inline bool MemoryArtifact::has_owner() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.owner_ != nullptr);
  return value;
}
inline const ::nds::identity::v1::PersonaId& MemoryArtifact::_internal_owner() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::nds::identity::v1::PersonaId* p = _impl_.owner_;
  return p != nullptr ? *p : reinterpret_cast<const ::nds::identity::v1::PersonaId&>(::nds::identity::v1::_PersonaId_default_instance_);
}
inline const ::nds::identity::v1::PersonaId& MemoryArtifact::owner() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.owner)
  return _internal_owner();
}
inline void MemoryArtifact::unsafe_arena_set_allocated_owner(
    ::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.owner_);
  }
  _impl_.owner_ = reinterpret_cast<::nds::identity::v1::PersonaId*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nds.memory.v1.MemoryArtifact.owner)
}
inline ::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE MemoryArtifact::release_owner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::nds::identity::v1::PersonaId* released = _impl_.owner_;
  _impl_.owner_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE MemoryArtifact::unsafe_arena_release_owner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryArtifact.owner)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::nds::identity::v1::PersonaId* temp = _impl_.owner_;
  _impl_.owner_ = nullptr;
  return temp;
}
inline ::nds::identity::v1::PersonaId* PROTOBUF_NONNULL MemoryArtifact::_internal_mutable_owner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.owner_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::nds::identity::v1::PersonaId>(GetArena());
    _impl_.owner_ = reinterpret_cast<::nds::identity::v1::PersonaId*>(p);
  }
  return _impl_.owner_;
}
inline ::nds::identity::v1::PersonaId* PROTOBUF_NONNULL MemoryArtifact::mutable_owner()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::nds::identity::v1::PersonaId* _msg = _internal_mutable_owner();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryArtifact.owner)
  return _msg;
}
inline void MemoryArtifact::set_allocated_owner(::nds::identity::v1::PersonaId* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.owner_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.owner_ = reinterpret_cast<::nds::identity::v1::PersonaId*>(value);
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryArtifact.owner)
}

// int32 schema_version = 3 [json_name = "schemaVersion"];
inline void MemoryArtifact::clear_schema_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.schema_version_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t MemoryArtifact::schema_version() const {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.schema_version)
  return _internal_schema_version();
}
inline void MemoryArtifact::set_schema_version(::int32_t value) {
  _internal_set_schema_version(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryArtifact.schema_version)
}
inline ::int32_t MemoryArtifact::_internal_schema_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.schema_version_;
}
inline void MemoryArtifact::_internal_set_schema_version(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.schema_version_ = value;
}

// optional string narrative = 10 [json_name = "narrative"];
inline bool MemoryArtifact::has_narrative() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void MemoryArtifact::clear_narrative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.narrative_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& MemoryArtifact::narrative() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.narrative)
  return _internal_narrative();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MemoryArtifact::set_narrative(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.narrative_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryArtifact.narrative)
}
inline ::std::string* PROTOBUF_NONNULL MemoryArtifact::mutable_narrative()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_narrative();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryArtifact.narrative)
  return _s;
}
inline const ::std::string& MemoryArtifact::_internal_narrative() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.narrative_.Get();
}
inline void MemoryArtifact::_internal_set_narrative(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.narrative_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MemoryArtifact::_internal_mutable_narrative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.narrative_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MemoryArtifact::release_narrative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryArtifact.narrative)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.narrative_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.narrative_.Set("", GetArena());
  }
  return released;
}
inline void MemoryArtifact::set_allocated_narrative(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.narrative_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.narrative_.IsDefault()) {
    _impl_.narrative_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryArtifact.narrative)
}

// repeated float embedding = 11 [json_name = "embedding", packed = true];
inline int MemoryArtifact::_internal_embedding_size() const {
  return _internal_embedding().size();
}
inline int MemoryArtifact::embedding_size() const {
  return _internal_embedding_size();
}
inline void MemoryArtifact::clear_embedding() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.embedding_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline float MemoryArtifact::embedding(int index) const {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.embedding)
  return _internal_embedding().Get(index);
}
inline void MemoryArtifact::set_embedding(int index, float value) {
  _internal_mutable_embedding()->Set(index, value);
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryArtifact.embedding)
}
inline void MemoryArtifact::add_embedding(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_embedding()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:nds.memory.v1.MemoryArtifact.embedding)
}
inline const ::google::protobuf::RepeatedField<float>& MemoryArtifact::embedding() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:nds.memory.v1.MemoryArtifact.embedding)
  return _internal_embedding();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL MemoryArtifact::mutable_embedding()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:nds.memory.v1.MemoryArtifact.embedding)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_embedding();
}
inline const ::google::protobuf::RepeatedField<float>&
MemoryArtifact::_internal_embedding() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.embedding_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
MemoryArtifact::_internal_mutable_embedding() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.embedding_;
}

// .nds.memory.v1.MemoryProof proof = 20 [json_name = "proof"];
inline bool MemoryArtifact::has_proof() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.proof_ != nullptr);
  return value;
}
inline void MemoryArtifact::clear_proof() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.proof_ != nullptr) _impl_.proof_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::nds::memory::v1::MemoryProof& MemoryArtifact::_internal_proof() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::nds::memory::v1::MemoryProof* p = _impl_.proof_;
  return p != nullptr ? *p : reinterpret_cast<const ::nds::memory::v1::MemoryProof&>(::nds::memory::v1::_MemoryProof_default_instance_);
}
inline const ::nds::memory::v1::MemoryProof& MemoryArtifact::proof() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.proof)
  return _internal_proof();
}
inline void MemoryArtifact::unsafe_arena_set_allocated_proof(
    ::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.proof_);
  }
  _impl_.proof_ = reinterpret_cast<::nds::memory::v1::MemoryProof*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nds.memory.v1.MemoryArtifact.proof)
}
inline ::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE MemoryArtifact::release_proof() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::nds::memory::v1::MemoryProof* released = _impl_.proof_;
  _impl_.proof_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE MemoryArtifact::unsafe_arena_release_proof() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nds.memory.v1.MemoryArtifact.proof)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::nds::memory::v1::MemoryProof* temp = _impl_.proof_;
  _impl_.proof_ = nullptr;
  return temp;
}
inline ::nds::memory::v1::MemoryProof* PROTOBUF_NONNULL MemoryArtifact::_internal_mutable_proof() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.proof_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::nds::memory::v1::MemoryProof>(GetArena());
    _impl_.proof_ = reinterpret_cast<::nds::memory::v1::MemoryProof*>(p);
  }
  return _impl_.proof_;
}
inline ::nds::memory::v1::MemoryProof* PROTOBUF_NONNULL MemoryArtifact::mutable_proof()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::nds::memory::v1::MemoryProof* _msg = _internal_mutable_proof();
  // @@protoc_insertion_point(field_mutable:nds.memory.v1.MemoryArtifact.proof)
  return _msg;
}
inline void MemoryArtifact::set_allocated_proof(::nds::memory::v1::MemoryProof* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.proof_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.proof_ = reinterpret_cast<::nds::memory::v1::MemoryProof*>(value);
  // @@protoc_insertion_point(field_set_allocated:nds.memory.v1.MemoryArtifact.proof)
}

// bool redacted = 30 [json_name = "redacted"];
inline void MemoryArtifact::clear_redacted() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redacted_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline bool MemoryArtifact::redacted() const {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.redacted)
  return _internal_redacted();
}
inline void MemoryArtifact::set_redacted(bool value) {
  _internal_set_redacted(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryArtifact.redacted)
}
inline bool MemoryArtifact::_internal_redacted() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.redacted_;
}
inline void MemoryArtifact::_internal_set_redacted(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redacted_ = value;
}

// optional .nds.memory.v1.RedactionReason redaction_reason = 31 [json_name = "redactionReason"];
inline bool MemoryArtifact::has_redaction_reason() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void MemoryArtifact::clear_redaction_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redaction_reason_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::nds::memory::v1::RedactionReason MemoryArtifact::redaction_reason() const {
  // @@protoc_insertion_point(field_get:nds.memory.v1.MemoryArtifact.redaction_reason)
  return _internal_redaction_reason();
}
inline void MemoryArtifact::set_redaction_reason(::nds::memory::v1::RedactionReason value) {
  _internal_set_redaction_reason(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:nds.memory.v1.MemoryArtifact.redaction_reason)
}
inline ::nds::memory::v1::RedactionReason MemoryArtifact::_internal_redaction_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::nds::memory::v1::RedactionReason>(_impl_.redaction_reason_);
}
inline void MemoryArtifact::_internal_set_redaction_reason(::nds::memory::v1::RedactionReason value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redaction_reason_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace memory
}  // namespace nds


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::nds::memory::v1::RedactionReason> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::nds::memory::v1::RedactionReason>() {
  return ::nds::memory::v1::RedactionReason_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // nds_2fmemory_2fv1_2fmemory_2eproto_2epb_2eh
