// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nds/audit/rationale.proto
// Protobuf C++ Version: 6.33.5

#include "nds/audit/rationale.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nds {
namespace audit {

inline constexpr NdsRationaleRef::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uri_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        mime_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR NdsRationaleRef::NdsRationaleRef(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NdsRationaleRef_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NdsRationaleRefDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NdsRationaleRefDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NdsRationaleRefDefaultTypeInternal() {}
  union {
    NdsRationaleRef _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NdsRationaleRefDefaultTypeInternal _NdsRationaleRef_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR NdsRationale_MetadataEntry_DoNotUse::NdsRationale_MetadataEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : NdsRationale_MetadataEntry_DoNotUse::MapEntry(NdsRationale_MetadataEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : NdsRationale_MetadataEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct NdsRationale_MetadataEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NdsRationale_MetadataEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NdsRationale_MetadataEntry_DoNotUseDefaultTypeInternal() {}
  union {
    NdsRationale_MetadataEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NdsRationale_MetadataEntry_DoNotUseDefaultTypeInternal _NdsRationale_MetadataEntry_DoNotUse_default_instance_;

inline constexpr NdsRationale::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        thought_path_{},
        evidence_event_ids_{},
        evidence_refs_{},
        source_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        confidence_{nullptr},
        risk_score_{nullptr},
        metadata_{} {}

template <typename>
PROTOBUF_CONSTEXPR NdsRationale::NdsRationale(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NdsRationale_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NdsRationaleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NdsRationaleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NdsRationaleDefaultTypeInternal() {}
  union {
    NdsRationale _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NdsRationaleDefaultTypeInternal _NdsRationale_default_instance_;
}  // namespace audit
}  // namespace nds
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_nds_2faudit_2frationale_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_nds_2faudit_2frationale_2eproto = nullptr;
const ::uint32_t
    TableStruct_nds_2faudit_2frationale_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale_MetadataEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale_MetadataEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale_MetadataEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_.source_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_.confidence_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_.thought_path_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_.evidence_event_ids_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_.evidence_refs_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_.risk_score_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationale, _impl_.metadata_),
        3,
        4,
        0,
        1,
        2,
        5,
        6,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationaleRef, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationaleRef, _impl_.uri_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationaleRef, _impl_.hash_),
        PROTOBUF_FIELD_OFFSET(::nds::audit::NdsRationaleRef, _impl_.mime_type_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::nds::audit::NdsRationale_MetadataEntry_DoNotUse)},
        {7, sizeof(::nds::audit::NdsRationale)},
        {24, sizeof(::nds::audit::NdsRationaleRef)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::nds::audit::_NdsRationale_MetadataEntry_DoNotUse_default_instance_._instance,
    &::nds::audit::_NdsRationale_default_instance_._instance,
    &::nds::audit::_NdsRationaleRef_default_instance_._instance,
};
const char descriptor_table_protodef_nds_2faudit_2frationale_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031nds/audit/rationale.proto\022\tnds.audit\032\027"
    "nds/common/common.proto\032\025nds/event/event"
    ".proto\"\335\003\n\014NdsRationale\022\026\n\006source\030\001 \001(\tR"
    "\006source\0228\n\nconfidence\030\002 \001(\0132\023.nds.common"
    ".DecimalH\000R\nconfidence\210\001\001\022!\n\014thought_pat"
    "h\030\003 \003(\tR\013thoughtPath\022@\n\022evidence_event_i"
    "ds\030\004 \003(\0132\022.nds.event.EventIdR\020evidenceEv"
    "entIds\022\?\n\revidence_refs\030\010 \003(\0132\032.nds.audi"
    "t.NdsRationaleRefR\014evidenceRefs\0227\n\nrisk_"
    "score\030\005 \001(\0132\023.nds.common.DecimalH\001R\trisk"
    "Score\210\001\001\022A\n\010metadata\030\006 \003(\0132%.nds.audit.N"
    "dsRationale.MetadataEntryR\010metadata\032;\n\rM"
    "etadataEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030"
    "\002 \001(\tR\005value:\0028\001B\r\n\013_confidenceB\r\n\013_risk"
    "_score\"u\n\017NdsRationaleRef\022\020\n\003uri\030\001 \001(\tR\003"
    "uri\022\027\n\004hash\030\002 \001(\tH\000R\004hash\210\001\001\022 \n\tmime_typ"
    "e\030\003 \001(\tH\001R\010mimeType\210\001\001B\007\n\005_hashB\014\n\n_mime"
    "_typeB\266\001\n4noie.linmimeng.noiedigitalsyst"
    "em.api.proto.nds.auditB\016RationaleProtoP\001"
    "Z)github.com/misty4119/nds-api/Go/nds/au"
    "dit\242\002\003NAX\252\002\tNds.Audit\312\002\tNds\\Audit\342\002\025Nds\\"
    "Audit\\GPBMetadata\352\002\nNds::Auditb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_nds_2faudit_2frationale_2eproto_deps[2] = {
        &::descriptor_table_nds_2fcommon_2fcommon_2eproto,
        &::descriptor_table_nds_2fevent_2fevent_2eproto,
};
static ::absl::once_flag descriptor_table_nds_2faudit_2frationale_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nds_2faudit_2frationale_2eproto = {
    false,
    false,
    878,
    descriptor_table_protodef_nds_2faudit_2frationale_2eproto,
    "nds/audit/rationale.proto",
    &descriptor_table_nds_2faudit_2frationale_2eproto_once,
    descriptor_table_nds_2faudit_2frationale_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_nds_2faudit_2frationale_2eproto::offsets,
    file_level_enum_descriptors_nds_2faudit_2frationale_2eproto,
    file_level_service_descriptors_nds_2faudit_2frationale_2eproto,
};
namespace nds {
namespace audit {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
NdsRationale_MetadataEntry_DoNotUse::NdsRationale_MetadataEntry_DoNotUse()
    : SuperType(NdsRationale_MetadataEntry_DoNotUse_class_data_.base()) {}
NdsRationale_MetadataEntry_DoNotUse::NdsRationale_MetadataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, NdsRationale_MetadataEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
NdsRationale_MetadataEntry_DoNotUse::NdsRationale_MetadataEntry_DoNotUse() : SuperType() {}
NdsRationale_MetadataEntry_DoNotUse::NdsRationale_MetadataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL NdsRationale_MetadataEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NdsRationale_MetadataEntry_DoNotUse(arena);
}
constexpr auto NdsRationale_MetadataEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NdsRationale_MetadataEntry_DoNotUse),
                                            alignof(NdsRationale_MetadataEntry_DoNotUse));
}
constexpr auto NdsRationale_MetadataEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NdsRationale_MetadataEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NdsRationale_MetadataEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NdsRationale_MetadataEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NdsRationale_MetadataEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&NdsRationale_MetadataEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NdsRationale_MetadataEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &NdsRationale_MetadataEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_nds_2faudit_2frationale_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NdsRationale_MetadataEntry_DoNotUse_class_data_ =
        NdsRationale_MetadataEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NdsRationale_MetadataEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NdsRationale_MetadataEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NdsRationale_MetadataEntry_DoNotUse_class_data_.tc_table);
  return NdsRationale_MetadataEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 53, 2>
NdsRationale_MetadataEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NdsRationale_MetadataEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NdsRationale_MetadataEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::audit::NdsRationale_MetadataEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2 [json_name = "value"];
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationale_MetadataEntry_DoNotUse, _impl_.value_)}},
    // string key = 1 [json_name = "key"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationale_MetadataEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1 [json_name = "key"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale_MetadataEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2 [json_name = "value"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale_MetadataEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\44\3\5\0\0\0\0\0"
    "nds.audit.NdsRationale.MetadataEntry"
    "key"
    "value"
  }},
};
// ===================================================================

class NdsRationale::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NdsRationale>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_._has_bits_);
};

void NdsRationale::clear_confidence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.confidence_ != nullptr) _impl_.confidence_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
void NdsRationale::clear_evidence_event_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.evidence_event_ids_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
void NdsRationale::clear_risk_score() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.risk_score_ != nullptr) _impl_.risk_score_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
NdsRationale::NdsRationale(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NdsRationale_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.audit.NdsRationale)
}
PROTOBUF_NDEBUG_INLINE NdsRationale::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::audit::NdsRationale& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        thought_path_{visibility, arena, from.thought_path_},
        evidence_event_ids_{visibility, arena, from.evidence_event_ids_},
        evidence_refs_{visibility, arena, from.evidence_refs_},
        source_(arena, from.source_),
        metadata_{visibility, arena, from.metadata_} {}

NdsRationale::NdsRationale(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NdsRationale& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NdsRationale_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NdsRationale* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.confidence_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.confidence_)
                : nullptr;
  _impl_.risk_score_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.risk_score_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:nds.audit.NdsRationale)
}
PROTOBUF_NDEBUG_INLINE NdsRationale::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        thought_path_{visibility, arena},
        evidence_event_ids_{visibility, arena},
        evidence_refs_{visibility, arena},
        source_(arena),
        metadata_{visibility, arena} {}

inline void NdsRationale::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, confidence_),
           0,
           offsetof(Impl_, risk_score_) -
               offsetof(Impl_, confidence_) +
               sizeof(Impl_::risk_score_));
}
NdsRationale::~NdsRationale() {
  // @@protoc_insertion_point(destructor:nds.audit.NdsRationale)
  SharedDtor(*this);
}
inline void NdsRationale::SharedDtor(MessageLite& self) {
  NdsRationale& this_ = static_cast<NdsRationale&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.source_.Destroy();
  delete this_._impl_.confidence_;
  delete this_._impl_.risk_score_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NdsRationale::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NdsRationale(arena);
}
constexpr auto NdsRationale::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.thought_path_) +
          decltype(NdsRationale::_impl_.thought_path_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.evidence_event_ids_) +
          decltype(NdsRationale::_impl_.evidence_event_ids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.evidence_refs_) +
          decltype(NdsRationale::_impl_.evidence_refs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.metadata_) +
          decltype(NdsRationale::_impl_.metadata_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(NdsRationale), alignof(NdsRationale), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&NdsRationale::PlacementNew_,
                                 sizeof(NdsRationale),
                                 alignof(NdsRationale));
  }
}
constexpr auto NdsRationale::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NdsRationale_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NdsRationale::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NdsRationale>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NdsRationale::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NdsRationale>(), &NdsRationale::ByteSizeLong,
              &NdsRationale::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_._cached_size_),
          false,
      },
      &NdsRationale::kDescriptorMethods,
      &descriptor_table_nds_2faudit_2frationale_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NdsRationale_class_data_ =
        NdsRationale::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NdsRationale::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NdsRationale_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NdsRationale_class_data_.tc_table);
  return NdsRationale_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 5, 57, 2>
NdsRationale::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    NdsRationale_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::audit::NdsRationale>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .nds.audit.NdsRationaleRef evidence_refs = 8 [json_name = "evidenceRefs"];
    {::_pbi::TcParser::FastMtR1,
     {66, 2, 3,
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.evidence_refs_)}},
    // string source = 1 [json_name = "source"];
    {::_pbi::TcParser::FastUS1,
     {10, 3, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.source_)}},
    // optional .nds.common.Decimal confidence = 2 [json_name = "confidence"];
    {::_pbi::TcParser::FastMtS1,
     {18, 4, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.confidence_)}},
    // repeated string thought_path = 3 [json_name = "thoughtPath"];
    {::_pbi::TcParser::FastUR1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.thought_path_)}},
    // repeated .nds.event.EventId evidence_event_ids = 4 [json_name = "evidenceEventIds"];
    {::_pbi::TcParser::FastMtR1,
     {34, 1, 1,
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.evidence_event_ids_)}},
    // optional .nds.common.Decimal risk_score = 5 [json_name = "riskScore"];
    {::_pbi::TcParser::FastMtS1,
     {42, 5, 2,
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.risk_score_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string source = 1 [json_name = "source"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.source_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .nds.common.Decimal confidence = 2 [json_name = "confidence"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.confidence_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated string thought_path = 3 [json_name = "thoughtPath"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.thought_path_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated .nds.event.EventId evidence_event_ids = 4 [json_name = "evidenceEventIds"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.evidence_event_ids_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .nds.common.Decimal risk_score = 5 [json_name = "riskScore"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.risk_score_), _Internal::kHasBitsOffset + 5, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // map<string, string> metadata = 6 [json_name = "metadata"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.metadata_), _Internal::kHasBitsOffset + 6, 4, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // repeated .nds.audit.NdsRationaleRef evidence_refs = 8 [json_name = "evidenceRefs"];
    {PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.evidence_refs_), _Internal::kHasBitsOffset + 2, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::nds::common::Decimal>()},
      {::_pbi::TcParser::GetTable<::nds::event::EventId>()},
      {::_pbi::TcParser::GetTable<::nds::common::Decimal>()},
      {::_pbi::TcParser::GetTable<::nds::audit::NdsRationaleRef>()},
      {::_pbi::TcParser::GetMapAuxInfo(
          1, 0, 9, 9, 0)},
  }},
  {{
    "\26\6\0\14\0\0\10\0"
    "nds.audit.NdsRationale"
    "source"
    "thought_path"
    "metadata"
  }},
};
PROTOBUF_NOINLINE void NdsRationale::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.audit.NdsRationale)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.thought_path_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.evidence_event_ids_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.evidence_refs_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.source_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.confidence_ != nullptr);
      _impl_.confidence_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.risk_score_ != nullptr);
      _impl_.risk_score_->Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      _impl_.metadata_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NdsRationale::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NdsRationale& this_ = static_cast<const NdsRationale&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NdsRationale::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NdsRationale& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.audit.NdsRationale)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string source = 1 [json_name = "source"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_source().empty()) {
      const ::std::string& _s = this_._internal_source();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationale.source");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // optional .nds.common.Decimal confidence = 2 [json_name = "confidence"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.confidence_, this_._impl_.confidence_->GetCachedSize(), target,
        stream);
  }

  // repeated string thought_path = 3 [json_name = "thoughtPath"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_thought_path_size(); i < n; ++i) {
      const auto& s = this_._internal_thought_path().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationale.thought_path");
      target = stream->WriteString(3, s, target);
    }
  }

  // repeated .nds.event.EventId evidence_event_ids = 4 [json_name = "evidenceEventIds"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_evidence_event_ids_size());
         i < n; i++) {
      const auto& repfield = this_._internal_evidence_event_ids().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              4, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // optional .nds.common.Decimal risk_score = 5 [json_name = "riskScore"];
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.risk_score_, this_._impl_.risk_score_->GetCachedSize(), target,
        stream);
  }

  // map<string, string> metadata = 6 [json_name = "metadata"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
    if (!this_._internal_metadata().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_metadata();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              6, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationale.metadata");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationale.metadata");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              6, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationale.metadata");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationale.metadata");
        }
      }
    }
  }

  // repeated .nds.audit.NdsRationaleRef evidence_refs = 8 [json_name = "evidenceRefs"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_evidence_refs_size());
         i < n; i++) {
      const auto& repfield = this_._internal_evidence_refs().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              8, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.audit.NdsRationale)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NdsRationale::ByteSizeLong(const MessageLite& base) {
  const NdsRationale& this_ = static_cast<const NdsRationale&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NdsRationale::ByteSizeLong() const {
  const NdsRationale& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.audit.NdsRationale)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // repeated string thought_path = 3 [json_name = "thoughtPath"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_thought_path().size());
      for (int i = 0, n = this_._internal_thought_path().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_thought_path().Get(i));
      }
    }
    // repeated .nds.event.EventId evidence_event_ids = 4 [json_name = "evidenceEventIds"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_evidence_event_ids_size();
      for (const auto& msg : this_._internal_evidence_event_ids()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .nds.audit.NdsRationaleRef evidence_refs = 8 [json_name = "evidenceRefs"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      total_size += 1UL * this_._internal_evidence_refs_size();
      for (const auto& msg : this_._internal_evidence_refs()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string source = 1 [json_name = "source"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_source().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_source());
      }
    }
    // optional .nds.common.Decimal confidence = 2 [json_name = "confidence"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.confidence_);
    }
    // optional .nds.common.Decimal risk_score = 5 [json_name = "riskScore"];
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.risk_score_);
    }
    // map<string, string> metadata = 6 [json_name = "metadata"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_metadata_size());
      for (const auto& entry : this_._internal_metadata()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NdsRationale::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<NdsRationale*>(&to_msg);
  auto& from = static_cast<const NdsRationale&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.audit.NdsRationale)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_thought_path()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_thought_path());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_evidence_event_ids()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_evidence_event_ids());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_evidence_refs()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_evidence_refs());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_source().empty()) {
        _this->_internal_set_source(from._internal_source());
      } else {
        if (_this->_impl_.source_.IsDefault()) {
          _this->_internal_set_source("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.confidence_ != nullptr);
      if (_this->_impl_.confidence_ == nullptr) {
        _this->_impl_.confidence_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.confidence_);
      } else {
        _this->_impl_.confidence_->MergeFrom(*from._impl_.confidence_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.risk_score_ != nullptr);
      if (_this->_impl_.risk_score_ == nullptr) {
        _this->_impl_.risk_score_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.risk_score_);
      } else {
        _this->_impl_.risk_score_->MergeFrom(*from._impl_.risk_score_);
      }
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      _this->_impl_.metadata_.MergeFrom(from._impl_.metadata_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NdsRationale::CopyFrom(const NdsRationale& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.audit.NdsRationale)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NdsRationale::InternalSwap(NdsRationale* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.thought_path_.InternalSwap(&other->_impl_.thought_path_);
  _impl_.evidence_event_ids_.InternalSwap(&other->_impl_.evidence_event_ids_);
  _impl_.evidence_refs_.InternalSwap(&other->_impl_.evidence_refs_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_, &other->_impl_.source_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.risk_score_)
      + sizeof(NdsRationale::_impl_.risk_score_)
      - PROTOBUF_FIELD_OFFSET(NdsRationale, _impl_.confidence_)>(
          reinterpret_cast<char*>(&_impl_.confidence_),
          reinterpret_cast<char*>(&other->_impl_.confidence_));
  _impl_.metadata_.InternalSwap(&other->_impl_.metadata_);
}

::google::protobuf::Metadata NdsRationale::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NdsRationaleRef::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NdsRationaleRef>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_._has_bits_);
};

NdsRationaleRef::NdsRationaleRef(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NdsRationaleRef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.audit.NdsRationaleRef)
}
PROTOBUF_NDEBUG_INLINE NdsRationaleRef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::audit::NdsRationaleRef& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uri_(arena, from.uri_),
        hash_(arena, from.hash_),
        mime_type_(arena, from.mime_type_) {}

NdsRationaleRef::NdsRationaleRef(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NdsRationaleRef& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NdsRationaleRef_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NdsRationaleRef* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nds.audit.NdsRationaleRef)
}
PROTOBUF_NDEBUG_INLINE NdsRationaleRef::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        uri_(arena),
        hash_(arena),
        mime_type_(arena) {}

inline void NdsRationaleRef::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NdsRationaleRef::~NdsRationaleRef() {
  // @@protoc_insertion_point(destructor:nds.audit.NdsRationaleRef)
  SharedDtor(*this);
}
inline void NdsRationaleRef::SharedDtor(MessageLite& self) {
  NdsRationaleRef& this_ = static_cast<NdsRationaleRef&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uri_.Destroy();
  this_._impl_.hash_.Destroy();
  this_._impl_.mime_type_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NdsRationaleRef::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NdsRationaleRef(arena);
}
constexpr auto NdsRationaleRef::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NdsRationaleRef),
                                            alignof(NdsRationaleRef));
}
constexpr auto NdsRationaleRef::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NdsRationaleRef_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NdsRationaleRef::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NdsRationaleRef>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NdsRationaleRef::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NdsRationaleRef>(), &NdsRationaleRef::ByteSizeLong,
              &NdsRationaleRef::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_._cached_size_),
          false,
      },
      &NdsRationaleRef::kDescriptorMethods,
      &descriptor_table_nds_2faudit_2frationale_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NdsRationaleRef_class_data_ =
        NdsRationaleRef::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NdsRationaleRef::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NdsRationaleRef_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NdsRationaleRef_class_data_.tc_table);
  return NdsRationaleRef_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 50, 2>
NdsRationaleRef::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NdsRationaleRef_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::audit::NdsRationaleRef>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string uri = 1 [json_name = "uri"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_.uri_)}},
    // optional string hash = 2 [json_name = "hash"];
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_.hash_)}},
    // optional string mime_type = 3 [json_name = "mimeType"];
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_.mime_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string uri = 1 [json_name = "uri"];
    {PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_.uri_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string hash = 2 [json_name = "hash"];
    {PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_.hash_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string mime_type = 3 [json_name = "mimeType"];
    {PROTOBUF_FIELD_OFFSET(NdsRationaleRef, _impl_.mime_type_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\3\4\11\0\0\0\0"
    "nds.audit.NdsRationaleRef"
    "uri"
    "hash"
    "mime_type"
  }},
};
PROTOBUF_NOINLINE void NdsRationaleRef::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.audit.NdsRationaleRef)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.uri_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.hash_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.mime_type_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NdsRationaleRef::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NdsRationaleRef& this_ = static_cast<const NdsRationaleRef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NdsRationaleRef::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NdsRationaleRef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.audit.NdsRationaleRef)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string uri = 1 [json_name = "uri"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_uri().empty()) {
      const ::std::string& _s = this_._internal_uri();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationaleRef.uri");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // optional string hash = 2 [json_name = "hash"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_hash();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationaleRef.hash");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string mime_type = 3 [json_name = "mimeType"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_mime_type();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.audit.NdsRationaleRef.mime_type");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.audit.NdsRationaleRef)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NdsRationaleRef::ByteSizeLong(const MessageLite& base) {
  const NdsRationaleRef& this_ = static_cast<const NdsRationaleRef&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NdsRationaleRef::ByteSizeLong() const {
  const NdsRationaleRef& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.audit.NdsRationaleRef)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string uri = 1 [json_name = "uri"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_uri().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_uri());
      }
    }
    // optional string hash = 2 [json_name = "hash"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_hash());
    }
    // optional string mime_type = 3 [json_name = "mimeType"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_mime_type());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NdsRationaleRef::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<NdsRationaleRef*>(&to_msg);
  auto& from = static_cast<const NdsRationaleRef&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.audit.NdsRationaleRef)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_uri().empty()) {
        _this->_internal_set_uri(from._internal_uri());
      } else {
        if (_this->_impl_.uri_.IsDefault()) {
          _this->_internal_set_uri("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_hash(from._internal_hash());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_mime_type(from._internal_mime_type());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NdsRationaleRef::CopyFrom(const NdsRationaleRef& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.audit.NdsRationaleRef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NdsRationaleRef::InternalSwap(NdsRationaleRef* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uri_, &other->_impl_.uri_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hash_, &other->_impl_.hash_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mime_type_, &other->_impl_.mime_type_, arena);
}

::google::protobuf::Metadata NdsRationaleRef::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace audit
}  // namespace nds
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_nds_2faudit_2frationale_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
