// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nds/asset/asset.proto
// Protobuf C++ Version: 6.33.5

#include "nds/asset/asset.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nds {
namespace asset {
template <typename>
PROTOBUF_CONSTEXPR NdsAsset_TagsEntry_DoNotUse::NdsAsset_TagsEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : NdsAsset_TagsEntry_DoNotUse::MapEntry(NdsAsset_TagsEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : NdsAsset_TagsEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct NdsAsset_TagsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NdsAsset_TagsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NdsAsset_TagsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    NdsAsset_TagsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NdsAsset_TagsEntry_DoNotUseDefaultTypeInternal _NdsAsset_TagsEntry_DoNotUse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR NdsAsset_MetadataEntry_DoNotUse::NdsAsset_MetadataEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : NdsAsset_MetadataEntry_DoNotUse::MapEntry(NdsAsset_MetadataEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : NdsAsset_MetadataEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct NdsAsset_MetadataEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NdsAsset_MetadataEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NdsAsset_MetadataEntry_DoNotUseDefaultTypeInternal() {}
  union {
    NdsAsset_MetadataEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NdsAsset_MetadataEntry_DoNotUseDefaultTypeInternal _NdsAsset_MetadataEntry_DoNotUse_default_instance_;

inline constexpr AssetId::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        scope_{static_cast< ::nds::asset::AssetScope >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR AssetId::AssetId(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AssetId_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AssetIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AssetIdDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AssetIdDefaultTypeInternal() {}
  union {
    AssetId _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AssetIdDefaultTypeInternal _AssetId_default_instance_;

inline constexpr NdsAsset::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        asset_id_{nullptr},
        limit_{nullptr},
        created_at_{::int64_t{0}},
        updated_at_{::int64_t{0}},
        tags_{},
        metadata_{} {}

template <typename>
PROTOBUF_CONSTEXPR NdsAsset::NdsAsset(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NdsAsset_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NdsAssetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NdsAssetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NdsAssetDefaultTypeInternal() {}
  union {
    NdsAsset _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NdsAssetDefaultTypeInternal _NdsAsset_default_instance_;
}  // namespace asset
}  // namespace nds
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_nds_2fasset_2fasset_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_nds_2fasset_2fasset_2eproto = nullptr;
const ::uint32_t
    TableStruct_nds_2fasset_2fasset_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::asset::AssetId, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::asset::AssetId, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::AssetId, _impl_.scope_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset_TagsEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset_TagsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset_TagsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset_MetadataEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset_MetadataEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset_MetadataEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset, _impl_.asset_id_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset, _impl_.tags_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset, _impl_.metadata_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset, _impl_.limit_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset, _impl_.created_at_),
        PROTOBUF_FIELD_OFFSET(::nds::asset::NdsAsset, _impl_.updated_at_),
        0,
        4,
        5,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::nds::asset::AssetId)},
        {7, sizeof(::nds::asset::NdsAsset_TagsEntry_DoNotUse)},
        {14, sizeof(::nds::asset::NdsAsset_MetadataEntry_DoNotUse)},
        {21, sizeof(::nds::asset::NdsAsset)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::nds::asset::_AssetId_default_instance_._instance,
    &::nds::asset::_NdsAsset_TagsEntry_DoNotUse_default_instance_._instance,
    &::nds::asset::_NdsAsset_MetadataEntry_DoNotUse_default_instance_._instance,
    &::nds::asset::_NdsAsset_default_instance_._instance,
};
const char descriptor_table_protodef_nds_2fasset_2fasset_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025nds/asset/asset.proto\022\tnds.asset\032\027nds/"
    "common/common.proto\"J\n\007AssetId\022\022\n\004name\030\001"
    " \001(\tR\004name\022+\n\005scope\030\002 \001(\0162\025.nds.asset.As"
    "setScopeR\005scope\"\231\003\n\010NdsAsset\022-\n\010asset_id"
    "\030\001 \001(\0132\022.nds.asset.AssetIdR\007assetId\0221\n\004t"
    "ags\030\002 \003(\0132\035.nds.asset.NdsAsset.TagsEntry"
    "R\004tags\022=\n\010metadata\030\003 \003(\0132!.nds.asset.Nds"
    "Asset.MetadataEntryR\010metadata\022.\n\005limit\030\004"
    " \001(\0132\023.nds.common.DecimalH\000R\005limit\210\001\001\022\035\n"
    "\ncreated_at\030\005 \001(\003R\tcreatedAt\022\035\n\nupdated_"
    "at\030\006 \001(\003R\tupdatedAt\0327\n\tTagsEntry\022\020\n\003key\030"
    "\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032;\n\r"
    "MetadataEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value"
    "\030\002 \001(\tR\005value:\0028\001B\010\n\006_limit*q\n\nAssetScop"
    "e\022\033\n\027ASSET_SCOPE_UNSPECIFIED\020\000\022\026\n\022ASSET_"
    "SCOPE_PLAYER\020\001\022\026\n\022ASSET_SCOPE_SERVER\020\002\022\026"
    "\n\022ASSET_SCOPE_GLOBAL\020\003B\262\001\n4noie.linmimen"
    "g.noiedigitalsystem.api.proto.nds.assetB"
    "\nAssetProtoP\001Z)github.com/misty4119/nds-"
    "api/Go/nds/asset\242\002\003NAX\252\002\tNds.Asset\312\002\tNds"
    "\\Asset\342\002\025Nds\\Asset\\GPBMetadata\352\002\nNds::As"
    "setb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_nds_2fasset_2fasset_2eproto_deps[1] = {
        &::descriptor_table_nds_2fcommon_2fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_nds_2fasset_2fasset_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nds_2fasset_2fasset_2eproto = {
    false,
    false,
    851,
    descriptor_table_protodef_nds_2fasset_2fasset_2eproto,
    "nds/asset/asset.proto",
    &descriptor_table_nds_2fasset_2fasset_2eproto_once,
    descriptor_table_nds_2fasset_2fasset_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_nds_2fasset_2fasset_2eproto::offsets,
    file_level_enum_descriptors_nds_2fasset_2fasset_2eproto,
    file_level_service_descriptors_nds_2fasset_2fasset_2eproto,
};
namespace nds {
namespace asset {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AssetScope_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nds_2fasset_2fasset_2eproto);
  return file_level_enum_descriptors_nds_2fasset_2fasset_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t AssetScope_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class AssetId::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AssetId>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AssetId, _impl_._has_bits_);
};

AssetId::AssetId(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AssetId_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.asset.AssetId)
}
PROTOBUF_NDEBUG_INLINE AssetId::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::asset::AssetId& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

AssetId::AssetId(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AssetId& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AssetId_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AssetId* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.scope_ = from._impl_.scope_;

  // @@protoc_insertion_point(copy_constructor:nds.asset.AssetId)
}
PROTOBUF_NDEBUG_INLINE AssetId::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void AssetId::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.scope_ = {};
}
AssetId::~AssetId() {
  // @@protoc_insertion_point(destructor:nds.asset.AssetId)
  SharedDtor(*this);
}
inline void AssetId::SharedDtor(MessageLite& self) {
  AssetId& this_ = static_cast<AssetId&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AssetId::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AssetId(arena);
}
constexpr auto AssetId::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AssetId),
                                            alignof(AssetId));
}
constexpr auto AssetId::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AssetId_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AssetId::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AssetId>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AssetId::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AssetId>(), &AssetId::ByteSizeLong,
              &AssetId::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AssetId, _impl_._cached_size_),
          false,
      },
      &AssetId::kDescriptorMethods,
      &descriptor_table_nds_2fasset_2fasset_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AssetId_class_data_ =
        AssetId::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AssetId::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AssetId_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AssetId_class_data_.tc_table);
  return AssetId_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2>
AssetId::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AssetId, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AssetId_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::asset::AssetId>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .nds.asset.AssetScope scope = 2 [json_name = "scope"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AssetId, _impl_.scope_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(AssetId, _impl_.scope_)}},
    // string name = 1 [json_name = "name"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(AssetId, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1 [json_name = "name"];
    {PROTOBUF_FIELD_OFFSET(AssetId, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .nds.asset.AssetScope scope = 2 [json_name = "scope"];
    {PROTOBUF_FIELD_OFFSET(AssetId, _impl_.scope_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\21\4\0\0\0\0\0\0"
    "nds.asset.AssetId"
    "name"
  }},
};
PROTOBUF_NOINLINE void AssetId::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.asset.AssetId)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_.scope_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AssetId::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AssetId& this_ = static_cast<const AssetId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AssetId::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AssetId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.asset.AssetId)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1 [json_name = "name"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.AssetId.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .nds.asset.AssetScope scope = 2 [json_name = "scope"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_scope() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_scope(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.asset.AssetId)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AssetId::ByteSizeLong(const MessageLite& base) {
  const AssetId& this_ = static_cast<const AssetId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AssetId::ByteSizeLong() const {
  const AssetId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.asset.AssetId)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string name = 1 [json_name = "name"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // .nds.asset.AssetScope scope = 2 [json_name = "scope"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_scope() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_scope());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AssetId::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AssetId*>(&to_msg);
  auto& from = static_cast<const AssetId&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.asset.AssetId)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_scope() != 0) {
        _this->_impl_.scope_ = from._impl_.scope_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AssetId::CopyFrom(const AssetId& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.asset.AssetId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AssetId::InternalSwap(AssetId* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.scope_, other->_impl_.scope_);
}

::google::protobuf::Metadata AssetId::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
NdsAsset_TagsEntry_DoNotUse::NdsAsset_TagsEntry_DoNotUse()
    : SuperType(NdsAsset_TagsEntry_DoNotUse_class_data_.base()) {}
NdsAsset_TagsEntry_DoNotUse::NdsAsset_TagsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, NdsAsset_TagsEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
NdsAsset_TagsEntry_DoNotUse::NdsAsset_TagsEntry_DoNotUse() : SuperType() {}
NdsAsset_TagsEntry_DoNotUse::NdsAsset_TagsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL NdsAsset_TagsEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NdsAsset_TagsEntry_DoNotUse(arena);
}
constexpr auto NdsAsset_TagsEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NdsAsset_TagsEntry_DoNotUse),
                                            alignof(NdsAsset_TagsEntry_DoNotUse));
}
constexpr auto NdsAsset_TagsEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NdsAsset_TagsEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NdsAsset_TagsEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NdsAsset_TagsEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NdsAsset_TagsEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&NdsAsset_TagsEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NdsAsset_TagsEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &NdsAsset_TagsEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_nds_2fasset_2fasset_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NdsAsset_TagsEntry_DoNotUse_class_data_ =
        NdsAsset_TagsEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NdsAsset_TagsEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NdsAsset_TagsEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NdsAsset_TagsEntry_DoNotUse_class_data_.tc_table);
  return NdsAsset_TagsEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 45, 2>
NdsAsset_TagsEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NdsAsset_TagsEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NdsAsset_TagsEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::asset::NdsAsset_TagsEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2 [json_name = "value"];
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(NdsAsset_TagsEntry_DoNotUse, _impl_.value_)}},
    // string key = 1 [json_name = "key"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NdsAsset_TagsEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1 [json_name = "key"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset_TagsEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2 [json_name = "value"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset_TagsEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\3\5\0\0\0\0\0"
    "nds.asset.NdsAsset.TagsEntry"
    "key"
    "value"
  }},
};
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
NdsAsset_MetadataEntry_DoNotUse::NdsAsset_MetadataEntry_DoNotUse()
    : SuperType(NdsAsset_MetadataEntry_DoNotUse_class_data_.base()) {}
NdsAsset_MetadataEntry_DoNotUse::NdsAsset_MetadataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, NdsAsset_MetadataEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
NdsAsset_MetadataEntry_DoNotUse::NdsAsset_MetadataEntry_DoNotUse() : SuperType() {}
NdsAsset_MetadataEntry_DoNotUse::NdsAsset_MetadataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL NdsAsset_MetadataEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NdsAsset_MetadataEntry_DoNotUse(arena);
}
constexpr auto NdsAsset_MetadataEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NdsAsset_MetadataEntry_DoNotUse),
                                            alignof(NdsAsset_MetadataEntry_DoNotUse));
}
constexpr auto NdsAsset_MetadataEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NdsAsset_MetadataEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NdsAsset_MetadataEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NdsAsset_MetadataEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NdsAsset_MetadataEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&NdsAsset_MetadataEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NdsAsset_MetadataEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &NdsAsset_MetadataEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_nds_2fasset_2fasset_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NdsAsset_MetadataEntry_DoNotUse_class_data_ =
        NdsAsset_MetadataEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NdsAsset_MetadataEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NdsAsset_MetadataEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NdsAsset_MetadataEntry_DoNotUse_class_data_.tc_table);
  return NdsAsset_MetadataEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2>
NdsAsset_MetadataEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NdsAsset_MetadataEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NdsAsset_MetadataEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::asset::NdsAsset_MetadataEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2 [json_name = "value"];
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(NdsAsset_MetadataEntry_DoNotUse, _impl_.value_)}},
    // string key = 1 [json_name = "key"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NdsAsset_MetadataEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1 [json_name = "key"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset_MetadataEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2 [json_name = "value"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset_MetadataEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\3\5\0\0\0\0\0"
    "nds.asset.NdsAsset.MetadataEntry"
    "key"
    "value"
  }},
};
// ===================================================================

class NdsAsset::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NdsAsset>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_._has_bits_);
};

void NdsAsset::clear_limit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.limit_ != nullptr) _impl_.limit_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
NdsAsset::NdsAsset(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NdsAsset_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.asset.NdsAsset)
}
PROTOBUF_NDEBUG_INLINE NdsAsset::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::asset::NdsAsset& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tags_{visibility, arena, from.tags_},
        metadata_{visibility, arena, from.metadata_} {}

NdsAsset::NdsAsset(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NdsAsset& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NdsAsset_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NdsAsset* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.asset_id_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.asset_id_)
                : nullptr;
  _impl_.limit_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.limit_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, created_at_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, created_at_),
           offsetof(Impl_, updated_at_) -
               offsetof(Impl_, created_at_) +
               sizeof(Impl_::updated_at_));

  // @@protoc_insertion_point(copy_constructor:nds.asset.NdsAsset)
}
PROTOBUF_NDEBUG_INLINE NdsAsset::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        tags_{visibility, arena},
        metadata_{visibility, arena} {}

inline void NdsAsset::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, asset_id_),
           0,
           offsetof(Impl_, updated_at_) -
               offsetof(Impl_, asset_id_) +
               sizeof(Impl_::updated_at_));
}
NdsAsset::~NdsAsset() {
  // @@protoc_insertion_point(destructor:nds.asset.NdsAsset)
  SharedDtor(*this);
}
inline void NdsAsset::SharedDtor(MessageLite& self) {
  NdsAsset& this_ = static_cast<NdsAsset&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.asset_id_;
  delete this_._impl_.limit_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NdsAsset::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NdsAsset(arena);
}
constexpr auto NdsAsset::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.tags_) +
          decltype(NdsAsset::_impl_.tags_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.metadata_) +
          decltype(NdsAsset::_impl_.metadata_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(NdsAsset), alignof(NdsAsset), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&NdsAsset::PlacementNew_,
                                 sizeof(NdsAsset),
                                 alignof(NdsAsset));
  }
}
constexpr auto NdsAsset::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NdsAsset_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NdsAsset::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NdsAsset>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NdsAsset::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NdsAsset>(), &NdsAsset::ByteSizeLong,
              &NdsAsset::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_._cached_size_),
          false,
      },
      &NdsAsset::kDescriptorMethods,
      &descriptor_table_nds_2fasset_2fasset_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NdsAsset_class_data_ =
        NdsAsset::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NdsAsset::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NdsAsset_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NdsAsset_class_data_.tc_table);
  return NdsAsset_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 4, 39, 2>
NdsAsset::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    NdsAsset_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::asset::NdsAsset>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .nds.asset.AssetId asset_id = 1 [json_name = "assetId"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.asset_id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional .nds.common.Decimal limit = 4 [json_name = "limit"];
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1,
      PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.limit_)}},
    // int64 created_at = 5 [json_name = "createdAt"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(NdsAsset, _impl_.created_at_), 2>(),
     {40, 2, 0,
      PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.created_at_)}},
    // int64 updated_at = 6 [json_name = "updatedAt"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(NdsAsset, _impl_.updated_at_), 3>(),
     {48, 3, 0,
      PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.updated_at_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .nds.asset.AssetId asset_id = 1 [json_name = "assetId"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.asset_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // map<string, string> tags = 2 [json_name = "tags"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.tags_), _Internal::kHasBitsOffset + 4, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // map<string, string> metadata = 3 [json_name = "metadata"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.metadata_), _Internal::kHasBitsOffset + 5, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // optional .nds.common.Decimal limit = 4 [json_name = "limit"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.limit_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int64 created_at = 5 [json_name = "createdAt"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.created_at_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 updated_at = 6 [json_name = "updatedAt"];
    {PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.updated_at_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::nds::asset::AssetId>()},
      {::_pbi::TcParser::GetTable<::nds::common::Decimal>()},
      {::_pbi::TcParser::GetMapAuxInfo(
          1, 0, 9, 9, 0)},
      {::_pbi::TcParser::GetMapAuxInfo(
          1, 0, 9, 9, 0)},
  }},
  {{
    "\22\0\4\10\0\0\0\0"
    "nds.asset.NdsAsset"
    "tags"
    "metadata"
  }},
};
PROTOBUF_NOINLINE void NdsAsset::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.asset.NdsAsset)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.asset_id_ != nullptr);
      _impl_.asset_id_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.limit_ != nullptr);
      _impl_.limit_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000003cU)) {
    ::memset(&_impl_.created_at_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.updated_at_) -
        reinterpret_cast<char*>(&_impl_.created_at_)) + sizeof(_impl_.updated_at_));
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      _impl_.tags_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      _impl_.metadata_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NdsAsset::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NdsAsset& this_ = static_cast<const NdsAsset&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NdsAsset::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NdsAsset& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.asset.NdsAsset)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .nds.asset.AssetId asset_id = 1 [json_name = "assetId"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.asset_id_, this_._impl_.asset_id_->GetCachedSize(), target,
        stream);
  }

  // map<string, string> tags = 2 [json_name = "tags"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_tags().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_tags();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.tags");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.tags");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.tags");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.tags");
        }
      }
    }
  }

  // map<string, string> metadata = 3 [json_name = "metadata"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_metadata().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_metadata();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              3, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.metadata");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.metadata");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              3, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.metadata");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.asset.NdsAsset.metadata");
        }
      }
    }
  }

  // optional .nds.common.Decimal limit = 4 [json_name = "limit"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.limit_, this_._impl_.limit_->GetCachedSize(), target,
        stream);
  }

  // int64 created_at = 5 [json_name = "createdAt"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_created_at() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<5>(
              stream, this_._internal_created_at(), target);
    }
  }

  // int64 updated_at = 6 [json_name = "updatedAt"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_updated_at() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<6>(
              stream, this_._internal_updated_at(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.asset.NdsAsset)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NdsAsset::ByteSizeLong(const MessageLite& base) {
  const NdsAsset& this_ = static_cast<const NdsAsset&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NdsAsset::ByteSizeLong() const {
  const NdsAsset& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.asset.NdsAsset)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // .nds.asset.AssetId asset_id = 1 [json_name = "assetId"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.asset_id_);
    }
    // optional .nds.common.Decimal limit = 4 [json_name = "limit"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.limit_);
    }
    // int64 created_at = 5 [json_name = "createdAt"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_created_at() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_created_at());
      }
    }
    // int64 updated_at = 6 [json_name = "updatedAt"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_updated_at() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_updated_at());
      }
    }
    // map<string, string> tags = 2 [json_name = "tags"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_tags_size());
      for (const auto& entry : this_._internal_tags()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
    // map<string, string> metadata = 3 [json_name = "metadata"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_metadata_size());
      for (const auto& entry : this_._internal_metadata()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NdsAsset::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<NdsAsset*>(&to_msg);
  auto& from = static_cast<const NdsAsset&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.asset.NdsAsset)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.asset_id_ != nullptr);
      if (_this->_impl_.asset_id_ == nullptr) {
        _this->_impl_.asset_id_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.asset_id_);
      } else {
        _this->_impl_.asset_id_->MergeFrom(*from._impl_.asset_id_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.limit_ != nullptr);
      if (_this->_impl_.limit_ == nullptr) {
        _this->_impl_.limit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.limit_);
      } else {
        _this->_impl_.limit_->MergeFrom(*from._impl_.limit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_created_at() != 0) {
        _this->_impl_.created_at_ = from._impl_.created_at_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_updated_at() != 0) {
        _this->_impl_.updated_at_ = from._impl_.updated_at_;
      }
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      _this->_impl_.tags_.MergeFrom(from._impl_.tags_);
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      _this->_impl_.metadata_.MergeFrom(from._impl_.metadata_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void NdsAsset::CopyFrom(const NdsAsset& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.asset.NdsAsset)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NdsAsset::InternalSwap(NdsAsset* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.updated_at_)
      + sizeof(NdsAsset::_impl_.updated_at_)
      - PROTOBUF_FIELD_OFFSET(NdsAsset, _impl_.asset_id_)>(
          reinterpret_cast<char*>(&_impl_.asset_id_),
          reinterpret_cast<char*>(&other->_impl_.asset_id_));
  _impl_.tags_.InternalSwap(&other->_impl_.tags_);
  _impl_.metadata_.InternalSwap(&other->_impl_.metadata_);
}

::google::protobuf::Metadata NdsAsset::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace asset
}  // namespace nds
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_nds_2fasset_2fasset_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
