// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies
// @generated from protobuf file "nds/context/context.proto" (package "nds.context", syntax proto3)
// tslint:disable
//
// [Module] NDS Protocol
// [Component] context.proto
// [Layer] Contract (language-agnostic)
// [Index] NDS-PROTO-CONTEXT-000
// [Semantic] Request context propagation + distributed tracing contract.
// [Constraint] Messages MUST remain immutable and replayable.
// [Since] 2.0.0
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// ============================================================================
// [Index] NDS-PROTO-CONTEXT-001 NdsContext
// ============================================================================

/**
 * [Semantic] Context + trace metadata used to correlate operations across boundaries.
 * [Behavior] This message is designed for observability (trace/correlation/span).
 * [SearchTag] tracing, correlation, observability, context-propagation
 *
 * @generated from protobuf message nds.context.NdsContext
 */
export interface NdsContext {
    /**
     * Trace ID (globally unique).
     * For distributed tracing. Recommended format: UUID.
     * All operations in the same request chain SHOULD share the same trace_id.
     *
     * @generated from protobuf field: string trace_id = 1
     */
    traceId: string;
    /**
     * Correlation ID.
     * Used to correlate related operations; MAY be equal to trace_id or different.
     * Commonly used to associate multiple independent requests into one business flow.
     *
     * @generated from protobuf field: string correlation_id = 2
     */
    correlationId: string;
    /**
     * Span ID (optional).
     * Identifies a specific node in the request chain.
     *
     * @generated from protobuf field: optional string span_id = 3
     */
    spanId?: string;
    /**
     * Parent span ID (optional).
     * Establishes parent-child relationships in the trace graph.
     *
     * @generated from protobuf field: optional string parent_span_id = 4
     */
    parentSpanId?: string;
    /**
     * Metadata.
     * Carries additional context values.
     *
     * @generated from protobuf field: map<string, string> meta = 5
     */
    meta: {
        [key: string]: string;
    };
    /**
     * Timestamp (Unix epoch milliseconds).
     * Context creation time.
     *
     * @generated from protobuf field: int64 timestamp = 6
     */
    timestamp: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class NdsContext$Type extends MessageType<NdsContext> {
    constructor() {
        super("nds.context.NdsContext", [
            { no: 1, name: "trace_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "correlation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "span_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "parent_span_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "meta", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 6, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<NdsContext>): NdsContext {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.traceId = "";
        message.correlationId = "";
        message.meta = {};
        message.timestamp = "0";
        if (value !== undefined)
            reflectionMergePartial<NdsContext>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NdsContext): NdsContext {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string trace_id */ 1:
                    message.traceId = reader.string();
                    break;
                case /* string correlation_id */ 2:
                    message.correlationId = reader.string();
                    break;
                case /* optional string span_id */ 3:
                    message.spanId = reader.string();
                    break;
                case /* optional string parent_span_id */ 4:
                    message.parentSpanId = reader.string();
                    break;
                case /* map<string, string> meta */ 5:
                    this.binaryReadMap5(message.meta, reader, options);
                    break;
                case /* int64 timestamp */ 6:
                    message.timestamp = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap5(map: NdsContext["meta"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof NdsContext["meta"] | undefined, val: NdsContext["meta"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for nds.context.NdsContext.meta");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: NdsContext, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string trace_id = 1; */
        if (message.traceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.traceId);
        /* string correlation_id = 2; */
        if (message.correlationId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.correlationId);
        /* optional string span_id = 3; */
        if (message.spanId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.spanId);
        /* optional string parent_span_id = 4; */
        if (message.parentSpanId !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.parentSpanId);
        /* map<string, string> meta = 5; */
        for (let k of globalThis.Object.keys(message.meta))
            writer.tag(5, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.meta[k]).join();
        /* int64 timestamp = 6; */
        if (message.timestamp !== "0")
            writer.tag(6, WireType.Varint).int64(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nds.context.NdsContext
 */
export const NdsContext = new NdsContext$Type();
