// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nds/event/v1/event_v1.proto
// Protobuf C++ Version: 6.33.5

#include "nds/event/v1/event_v1.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nds {
namespace event {
namespace v1 {

inline constexpr Cursor::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Cursor::Cursor(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Cursor_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CursorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CursorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CursorDefaultTypeInternal() {}
  union {
    Cursor _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CursorDefaultTypeInternal _Cursor_default_instance_;

inline constexpr EventEnvelope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        extensions_{},
        event_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        request_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cursor_{nullptr},
        occurred_at_{nullptr},
        actor_{nullptr},
        owner_{nullptr},
        payload_{nullptr},
        ctx_{nullptr},
        type_{static_cast< ::nds::event::v1::EventType >(0)},
        schema_version_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EventEnvelope::EventEnvelope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EventEnvelope_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EventEnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventEnvelopeDefaultTypeInternal() {}
  union {
    EventEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventEnvelopeDefaultTypeInternal _EventEnvelope_default_instance_;
}  // namespace v1
}  // namespace event
}  // namespace nds
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_nds_2fevent_2fv1_2fevent_5fv1_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_nds_2fevent_2fv1_2fevent_5fv1_2eproto = nullptr;
const ::uint32_t
    TableStruct_nds_2fevent_2fv1_2fevent_5fv1_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::Cursor, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::Cursor, _impl_.value_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_._has_bits_),
        14, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.event_id_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.cursor_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.occurred_at_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.actor_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.owner_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.schema_version_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.extensions_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.ctx_),
        PROTOBUF_FIELD_OFFSET(::nds::event::v1::EventEnvelope, _impl_.request_id_),
        1,
        3,
        4,
        5,
        6,
        9,
        10,
        7,
        0,
        8,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::nds::event::v1::Cursor)},
        {5, sizeof(::nds::event::v1::EventEnvelope)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::nds::event::v1::_Cursor_default_instance_._instance,
    &::nds::event::v1::_EventEnvelope_default_instance_._instance,
};
const char descriptor_table_protodef_nds_2fevent_2fv1_2fevent_5fv1_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033nds/event/v1/event_v1.proto\022\014nds.event"
    ".v1\032\031google/protobuf/any.proto\032\037google/p"
    "rotobuf/timestamp.proto\032\035nds/common/v1/c"
    "ommon_v1.proto\032!nds/identity/v1/identity"
    "_v1.proto\"\036\n\006Cursor\022\024\n\005value\030\001 \001(\014R\005valu"
    "e\"\263\004\n\rEventEnvelope\022\031\n\010event_id\030\001 \001(\014R\007e"
    "ventId\022,\n\006cursor\030\002 \001(\0132\024.nds.event.v1.Cu"
    "rsorR\006cursor\022;\n\013occurred_at\030\003 \001(\0132\032.goog"
    "le.protobuf.TimestampR\noccurredAt\0220\n\005act"
    "or\030\n \001(\0132\032.nds.identity.v1.PersonaIdR\005ac"
    "tor\0225\n\005owner\030\013 \001(\0132\032.nds.identity.v1.Per"
    "sonaIdH\000R\005owner\210\001\001\022+\n\004type\030\024 \001(\0162\027.nds.e"
    "vent.v1.EventTypeR\004type\022%\n\016schema_versio"
    "n\030\025 \001(\005R\rschemaVersion\022.\n\007payload\030\036 \001(\0132"
    "\024.google.protobuf.AnyR\007payload\0224\n\nextens"
    "ions\030\037 \003(\0132\024.google.protobuf.AnyR\nextens"
    "ions\0224\n\003ctx\030( \001(\0132\035.nds.common.v1.Reques"
    "tContextH\001R\003ctx\210\001\001\022\"\n\nrequest_id\030) \001(\tH\002"
    "R\trequestId\210\001\001B\010\n\006_ownerB\006\n\004_ctxB\r\n\013_req"
    "uest_id*\272\001\n\tEventType\022\032\n\026EVENT_TYPE_UNSP"
    "ECIFIED\020\000\022\"\n\036EVENT_TYPE_LEDGER_TX_COMMIT"
    "TED\020\001\022%\n!EVENT_TYPE_LEDGER_BALANCE_CHANG"
    "ED\020\002\022\035\n\031EVENT_TYPE_IDENTITY_BOUND\020\n\022\'\n#E"
    "VENT_TYPE_MEMORY_ARTIFACT_ANCHORED\020\024B\317\001\n"
    "7noie.linmimeng.noiedigitalsystem.api.pr"
    "oto.nds.event.v1B\014EventV1ProtoP\001Z4github"
    ".com/misty4119/nds-api/Go/nds/event/v1;e"
    "ventv1\242\002\003NEX\252\002\014Nds.Event.V1\312\002\014Nds\\Event\\"
    "V1\342\002\030Nds\\Event\\V1\\GPBMetadata\352\002\016Nds::Eve"
    "nt::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto_deps[4] = {
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
        &::descriptor_table_nds_2fcommon_2fv1_2fcommon_5fv1_2eproto,
        &::descriptor_table_nds_2fidentity_2fv1_2fidentity_5fv1_2eproto,
};
static ::absl::once_flag descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto = {
    false,
    false,
    1174,
    descriptor_table_protodef_nds_2fevent_2fv1_2fevent_5fv1_2eproto,
    "nds/event/v1/event_v1.proto",
    &descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto_once,
    descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto_deps,
    4,
    2,
    schemas,
    file_default_instances,
    TableStruct_nds_2fevent_2fv1_2fevent_5fv1_2eproto::offsets,
    file_level_enum_descriptors_nds_2fevent_2fv1_2fevent_5fv1_2eproto,
    file_level_service_descriptors_nds_2fevent_2fv1_2fevent_5fv1_2eproto,
};
namespace nds {
namespace event {
namespace v1 {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EventType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto);
  return file_level_enum_descriptors_nds_2fevent_2fv1_2fevent_5fv1_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EventType_internal_data_[] = {
    196608u, 32u, 131200u, };
// ===================================================================

class Cursor::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Cursor>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Cursor, _impl_._has_bits_);
};

Cursor::Cursor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Cursor_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.event.v1.Cursor)
}
PROTOBUF_NDEBUG_INLINE Cursor::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::event::v1::Cursor& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_(arena, from.value_) {}

Cursor::Cursor(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Cursor& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Cursor_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Cursor* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nds.event.v1.Cursor)
}
PROTOBUF_NDEBUG_INLINE Cursor::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        value_(arena) {}

inline void Cursor::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Cursor::~Cursor() {
  // @@protoc_insertion_point(destructor:nds.event.v1.Cursor)
  SharedDtor(*this);
}
inline void Cursor::SharedDtor(MessageLite& self) {
  Cursor& this_ = static_cast<Cursor&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Cursor::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Cursor(arena);
}
constexpr auto Cursor::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Cursor),
                                            alignof(Cursor));
}
constexpr auto Cursor::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Cursor_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Cursor::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Cursor>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Cursor::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Cursor>(), &Cursor::ByteSizeLong,
              &Cursor::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Cursor, _impl_._cached_size_),
          false,
      },
      &Cursor::kDescriptorMethods,
      &descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Cursor_class_data_ =
        Cursor::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Cursor::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Cursor_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Cursor_class_data_.tc_table);
  return Cursor_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Cursor::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Cursor, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Cursor_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::event::v1::Cursor>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes value = 1 [json_name = "value"];
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Cursor, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes value = 1 [json_name = "value"];
    {PROTOBUF_FIELD_OFFSET(Cursor, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Cursor::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.event.v1.Cursor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.value_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Cursor::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Cursor& this_ = static_cast<const Cursor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Cursor::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Cursor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.event.v1.Cursor)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes value = 1 [json_name = "value"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.event.v1.Cursor)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Cursor::ByteSizeLong(const MessageLite& base) {
  const Cursor& this_ = static_cast<const Cursor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Cursor::ByteSizeLong() const {
  const Cursor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.event.v1.Cursor)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bytes value = 1 [json_name = "value"];
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Cursor::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Cursor*>(&to_msg);
  auto& from = static_cast<const Cursor&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.event.v1.Cursor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_value().empty()) {
      _this->_internal_set_value(from._internal_value());
    } else {
      if (_this->_impl_.value_.IsDefault()) {
        _this->_internal_set_value("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Cursor::CopyFrom(const Cursor& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.event.v1.Cursor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Cursor::InternalSwap(Cursor* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata Cursor::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EventEnvelope::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EventEnvelope>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_._has_bits_);
};

void EventEnvelope::clear_occurred_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.occurred_at_ != nullptr) _impl_.occurred_at_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
void EventEnvelope::clear_actor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.actor_ != nullptr) _impl_.actor_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
void EventEnvelope::clear_owner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.owner_ != nullptr) _impl_.owner_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
void EventEnvelope::clear_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.payload_ != nullptr) _impl_.payload_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
void EventEnvelope::clear_extensions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extensions_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
void EventEnvelope::clear_ctx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ctx_ != nullptr) _impl_.ctx_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
EventEnvelope::EventEnvelope(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EventEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nds.event.v1.EventEnvelope)
}
PROTOBUF_NDEBUG_INLINE EventEnvelope::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nds::event::v1::EventEnvelope& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        extensions_{visibility, arena, from.extensions_},
        event_id_(arena, from.event_id_),
        request_id_(arena, from.request_id_) {}

EventEnvelope::EventEnvelope(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EventEnvelope& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EventEnvelope_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EventEnvelope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.cursor_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cursor_)
                : nullptr;
  _impl_.occurred_at_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.occurred_at_)
                : nullptr;
  _impl_.actor_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.actor_)
                : nullptr;
  _impl_.owner_ = (CheckHasBit(cached_has_bits, 0x00000040U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.owner_)
                : nullptr;
  _impl_.payload_ = (CheckHasBit(cached_has_bits, 0x00000080U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_)
                : nullptr;
  _impl_.ctx_ = (CheckHasBit(cached_has_bits, 0x00000100U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ctx_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, schema_version_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::schema_version_));

  // @@protoc_insertion_point(copy_constructor:nds.event.v1.EventEnvelope)
}
PROTOBUF_NDEBUG_INLINE EventEnvelope::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        extensions_{visibility, arena},
        event_id_(arena),
        request_id_(arena) {}

inline void EventEnvelope::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, cursor_),
           0,
           offsetof(Impl_, schema_version_) -
               offsetof(Impl_, cursor_) +
               sizeof(Impl_::schema_version_));
}
EventEnvelope::~EventEnvelope() {
  // @@protoc_insertion_point(destructor:nds.event.v1.EventEnvelope)
  SharedDtor(*this);
}
inline void EventEnvelope::SharedDtor(MessageLite& self) {
  EventEnvelope& this_ = static_cast<EventEnvelope&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.event_id_.Destroy();
  this_._impl_.request_id_.Destroy();
  delete this_._impl_.cursor_;
  delete this_._impl_.occurred_at_;
  delete this_._impl_.actor_;
  delete this_._impl_.owner_;
  delete this_._impl_.payload_;
  delete this_._impl_.ctx_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EventEnvelope::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EventEnvelope(arena);
}
constexpr auto EventEnvelope::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.extensions_) +
          decltype(EventEnvelope::_impl_.extensions_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(EventEnvelope), alignof(EventEnvelope), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EventEnvelope::PlacementNew_,
                                 sizeof(EventEnvelope),
                                 alignof(EventEnvelope));
  }
}
constexpr auto EventEnvelope::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EventEnvelope_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EventEnvelope::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EventEnvelope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EventEnvelope::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EventEnvelope>(), &EventEnvelope::ByteSizeLong,
              &EventEnvelope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_._cached_size_),
          false,
      },
      &EventEnvelope::kDescriptorMethods,
      &descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EventEnvelope_class_data_ =
        EventEnvelope::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EventEnvelope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EventEnvelope_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EventEnvelope_class_data_.tc_table);
  return EventEnvelope_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 7, 53, 7>
EventEnvelope::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_._has_bits_),
    0, // no _extensions_
    41, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    2682780152,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    7,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EventEnvelope_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nds::event::v1::EventEnvelope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes event_id = 1 [json_name = "eventId"];
    {::_pbi::TcParser::FastBS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.event_id_)}},
    // .nds.event.v1.Cursor cursor = 2 [json_name = "cursor"];
    {::_pbi::TcParser::FastMtS1,
     {18, 3, 0,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.cursor_)}},
    // .google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];
    {::_pbi::TcParser::FastMtS1,
     {26, 4, 1,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.occurred_at_)}},
    // .nds.event.v1.EventType type = 20 [json_name = "type"];
    {::_pbi::TcParser::FastV32S2,
     {416, 9, 0,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.type_)}},
    // int32 schema_version = 21 [json_name = "schemaVersion"];
    {::_pbi::TcParser::FastV32S2,
     {424, 10, 0,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.schema_version_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional .nds.common.v1.RequestContext ctx = 40 [json_name = "ctx"];
    {::_pbi::TcParser::FastMtS2,
     {706, 8, 6,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.ctx_)}},
    // optional string request_id = 41 [json_name = "requestId"];
    {::_pbi::TcParser::FastUS2,
     {714, 2, 0,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.request_id_)}},
    // .nds.identity.v1.PersonaId actor = 10 [json_name = "actor"];
    {::_pbi::TcParser::FastMtS1,
     {82, 5, 2,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.actor_)}},
    // optional .nds.identity.v1.PersonaId owner = 11 [json_name = "owner"];
    {::_pbi::TcParser::FastMtS1,
     {90, 6, 3,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.owner_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // .google.protobuf.Any payload = 30 [json_name = "payload"];
    {::_pbi::TcParser::FastMtS2,
     {498, 7, 4,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.payload_)}},
    // repeated .google.protobuf.Any extensions = 31 [json_name = "extensions"];
    {::_pbi::TcParser::FastMtR2,
     {506, 0, 5,
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.extensions_)}},
  }}, {{
    40, 0, 1,
    65532, 9,
    65535, 65535
  }}, {{
    // bytes event_id = 1 [json_name = "eventId"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.event_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // .nds.event.v1.Cursor cursor = 2 [json_name = "cursor"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.cursor_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.occurred_at_), _Internal::kHasBitsOffset + 4, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .nds.identity.v1.PersonaId actor = 10 [json_name = "actor"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.actor_), _Internal::kHasBitsOffset + 5, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .nds.identity.v1.PersonaId owner = 11 [json_name = "owner"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.owner_), _Internal::kHasBitsOffset + 6, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .nds.event.v1.EventType type = 20 [json_name = "type"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.type_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int32 schema_version = 21 [json_name = "schemaVersion"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.schema_version_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // .google.protobuf.Any payload = 30 [json_name = "payload"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.payload_), _Internal::kHasBitsOffset + 7, 4, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .google.protobuf.Any extensions = 31 [json_name = "extensions"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.extensions_), _Internal::kHasBitsOffset + 0, 5, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .nds.common.v1.RequestContext ctx = 40 [json_name = "ctx"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.ctx_), _Internal::kHasBitsOffset + 8, 6, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string request_id = 41 [json_name = "requestId"];
    {PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.request_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::nds::event::v1::Cursor>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::nds::identity::v1::PersonaId>()},
      {::_pbi::TcParser::GetTable<::nds::identity::v1::PersonaId>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
      {::_pbi::TcParser::GetTable<::nds::common::v1::RequestContext>()},
  }},
  {{
    "\32\0\0\0\0\0\0\0\0\0\0\12\0\0\0\0"
    "nds.event.v1.EventEnvelope"
    "request_id"
  }},
};
PROTOBUF_NOINLINE void EventEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:nds.event.v1.EventEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.extensions_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.event_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.request_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.cursor_ != nullptr);
      _impl_.cursor_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.occurred_at_ != nullptr);
      _impl_.occurred_at_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.actor_ != nullptr);
      _impl_.actor_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(_impl_.owner_ != nullptr);
      _impl_.owner_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(_impl_.payload_ != nullptr);
      _impl_.payload_->Clear();
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    ABSL_DCHECK(_impl_.ctx_ != nullptr);
    _impl_.ctx_->Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000600U)) {
    ::memset(&_impl_.type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.schema_version_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.schema_version_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EventEnvelope::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EventEnvelope& this_ = static_cast<const EventEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EventEnvelope::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EventEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nds.event.v1.EventEnvelope)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes event_id = 1 [json_name = "eventId"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_event_id().empty()) {
      const ::std::string& _s = this_._internal_event_id();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // .nds.event.v1.Cursor cursor = 2 [json_name = "cursor"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.cursor_, this_._impl_.cursor_->GetCachedSize(), target,
        stream);
  }

  // .google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.occurred_at_, this_._impl_.occurred_at_->GetCachedSize(), target,
        stream);
  }

  // .nds.identity.v1.PersonaId actor = 10 [json_name = "actor"];
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        10, *this_._impl_.actor_, this_._impl_.actor_->GetCachedSize(), target,
        stream);
  }

  // optional .nds.identity.v1.PersonaId owner = 11 [json_name = "owner"];
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        11, *this_._impl_.owner_, this_._impl_.owner_->GetCachedSize(), target,
        stream);
  }

  // .nds.event.v1.EventType type = 20 [json_name = "type"];
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          20, this_._internal_type(), target);
    }
  }

  // int32 schema_version = 21 [json_name = "schemaVersion"];
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (this_._internal_schema_version() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteInt32ToArray(
          21, this_._internal_schema_version(), target);
    }
  }

  // .google.protobuf.Any payload = 30 [json_name = "payload"];
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        30, *this_._impl_.payload_, this_._impl_.payload_->GetCachedSize(), target,
        stream);
  }

  // repeated .google.protobuf.Any extensions = 31 [json_name = "extensions"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_extensions_size());
         i < n; i++) {
      const auto& repfield = this_._internal_extensions().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              31, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // optional .nds.common.v1.RequestContext ctx = 40 [json_name = "ctx"];
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        40, *this_._impl_.ctx_, this_._impl_.ctx_->GetCachedSize(), target,
        stream);
  }

  // optional string request_id = 41 [json_name = "requestId"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_request_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nds.event.v1.EventEnvelope.request_id");
    target = stream->WriteStringMaybeAliased(41, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nds.event.v1.EventEnvelope)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EventEnvelope::ByteSizeLong(const MessageLite& base) {
  const EventEnvelope& this_ = static_cast<const EventEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EventEnvelope::ByteSizeLong() const {
  const EventEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nds.event.v1.EventEnvelope)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated .google.protobuf.Any extensions = 31 [json_name = "extensions"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 2UL * this_._internal_extensions_size();
      for (const auto& msg : this_._internal_extensions()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // bytes event_id = 1 [json_name = "eventId"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_event_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_event_id());
      }
    }
    // optional string request_id = 41 [json_name = "requestId"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_request_id());
    }
    // .nds.event.v1.Cursor cursor = 2 [json_name = "cursor"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cursor_);
    }
    // .google.protobuf.Timestamp occurred_at = 3 [json_name = "occurredAt"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.occurred_at_);
    }
    // .nds.identity.v1.PersonaId actor = 10 [json_name = "actor"];
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.actor_);
    }
    // optional .nds.identity.v1.PersonaId owner = 11 [json_name = "owner"];
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.owner_);
    }
    // .google.protobuf.Any payload = 30 [json_name = "payload"];
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_);
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    // optional .nds.common.v1.RequestContext ctx = 40 [json_name = "ctx"];
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ctx_);
    }
    // .nds.event.v1.EventType type = 20 [json_name = "type"];
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_type() != 0) {
        total_size += 2 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
    // int32 schema_version = 21 [json_name = "schemaVersion"];
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (this_._internal_schema_version() != 0) {
        total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                        this_._internal_schema_version());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EventEnvelope::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EventEnvelope*>(&to_msg);
  auto& from = static_cast<const EventEnvelope&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nds.event.v1.EventEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_extensions()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_extensions());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_event_id().empty()) {
        _this->_internal_set_event_id(from._internal_event_id());
      } else {
        if (_this->_impl_.event_id_.IsDefault()) {
          _this->_internal_set_event_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_request_id(from._internal_request_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.cursor_ != nullptr);
      if (_this->_impl_.cursor_ == nullptr) {
        _this->_impl_.cursor_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.cursor_);
      } else {
        _this->_impl_.cursor_->MergeFrom(*from._impl_.cursor_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.occurred_at_ != nullptr);
      if (_this->_impl_.occurred_at_ == nullptr) {
        _this->_impl_.occurred_at_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.occurred_at_);
      } else {
        _this->_impl_.occurred_at_->MergeFrom(*from._impl_.occurred_at_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.actor_ != nullptr);
      if (_this->_impl_.actor_ == nullptr) {
        _this->_impl_.actor_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.actor_);
      } else {
        _this->_impl_.actor_->MergeFrom(*from._impl_.actor_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(from._impl_.owner_ != nullptr);
      if (_this->_impl_.owner_ == nullptr) {
        _this->_impl_.owner_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.owner_);
      } else {
        _this->_impl_.owner_->MergeFrom(*from._impl_.owner_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(from._impl_.payload_ != nullptr);
      if (_this->_impl_.payload_ == nullptr) {
        _this->_impl_.payload_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_);
      } else {
        _this->_impl_.payload_->MergeFrom(*from._impl_.payload_);
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      ABSL_DCHECK(from._impl_.ctx_ != nullptr);
      if (_this->_impl_.ctx_ == nullptr) {
        _this->_impl_.ctx_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ctx_);
      } else {
        _this->_impl_.ctx_->MergeFrom(*from._impl_.ctx_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (from._internal_schema_version() != 0) {
        _this->_impl_.schema_version_ = from._impl_.schema_version_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void EventEnvelope::CopyFrom(const EventEnvelope& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nds.event.v1.EventEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EventEnvelope::InternalSwap(EventEnvelope* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.extensions_.InternalSwap(&other->_impl_.extensions_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.event_id_, &other->_impl_.event_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.request_id_, &other->_impl_.request_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.schema_version_)
      + sizeof(EventEnvelope::_impl_.schema_version_)
      - PROTOBUF_FIELD_OFFSET(EventEnvelope, _impl_.cursor_)>(
          reinterpret_cast<char*>(&_impl_.cursor_),
          reinterpret_cast<char*>(&other->_impl_.cursor_));
}

::google::protobuf::Metadata EventEnvelope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace event
}  // namespace nds
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_nds_2fevent_2fv1_2fevent_5fv1_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
